package service

import (
	"crypto/rand"
	"database/sql"
	"encoding/base64"
	"fmt"
	"time"

	"github.com/webappsgo/wthr/src/common/i18n"
	"github.com/webappsgo/wthr/src/server/model"
	"github.com/webappsgo/wthr/src/util"
)

const DefaultAdminInviteExpiration = "24h"

var adminInviteExpirations = map[string]time.Duration{
	"1h":  time.Hour,
	"6h":  6 * time.Hour,
	"24h": 24 * time.Hour,
	"48h": 48 * time.Hour,
	"7d":  7 * 24 * time.Hour,
}

// AdminInviteService handles admin invitation logic
type AdminInviteService struct {
	DB           *sql.DB
	InviteModel  *model.AdminInviteModel
	AdminModel   *model.AdminModel
	EmailService *SMTPService
	BaseURL      string
}

// NewAdminInviteService creates a new admin invite service
func NewAdminInviteService(db *sql.DB, baseURL string, emailService *SMTPService) *AdminInviteService {
	return &AdminInviteService{
		DB:           db,
		InviteModel:  &model.AdminInviteModel{DB: db},
		AdminModel:   &model.AdminModel{DB: db},
		EmailService: emailService,
		BaseURL:      baseURL,
	}
}

// ParseAdminInviteExpiration validates the allowed invite expiration values.
func ParseAdminInviteExpiration(value string) (string, time.Duration, error) {
	normalized := value
	if normalized == "" {
		normalized = DefaultAdminInviteExpiration
	}

	expiresIn, ok := adminInviteExpirations[normalized]
	if !ok {
		return "", 0, fmt.Errorf("invalid invite expiration, allowed values: 1h, 6h, 24h, 48h, 7d")
	}

	return normalized, expiresIn, nil
}

// GenerateInviteToken generates a cryptographically secure random token
func (s *AdminInviteService) GenerateInviteToken() (string, error) {
	// Generate 32 random bytes
	tokenBytes := make([]byte, 32)
	if _, err := rand.Read(tokenBytes); err != nil {
		return "", fmt.Errorf("failed to generate random token: %w", err)
	}

	// Encode as URL-safe base64
	token := base64.URLEncoding.EncodeToString(tokenBytes)
	return token, nil
}

// CreateInvite creates a new admin invitation
func (s *AdminInviteService) CreateInvite(email string, invitedByID int, expiration string) (*model.AdminInvite, string, error) {
	normalizedEmail := util.NormalizeEmail(email)
	if err := util.ValidateEmail(normalizedEmail); err != nil {
		return nil, "", err
	}

	normalizedExpiration, expiresIn, err := ParseAdminInviteExpiration(expiration)
	if err != nil {
		return nil, "", err
	}

	// Check if inviter is a valid admin
	_, err = s.AdminModel.GetByID(int64(invitedByID))
	if err != nil {
		return nil, "", fmt.Errorf("inviter admin not found: %w", err)
	}

	// Check if email is already an admin
	existingAdmin, err := s.AdminModel.GetByEmail(normalizedEmail)
	if err == nil && existingAdmin != nil {
		return nil, "", fmt.Errorf("email is already registered as admin")
	}

	// Generate secure token (will be generated by InviteModel.CreateInvite)
	// Create invite in database
	invite, err := s.InviteModel.CreateInvite(normalizedEmail, int64(invitedByID), expiresIn)
	if err != nil {
		return nil, "", err
	}

	// Send invitation email when SMTP is configured
	if s.EmailService != nil && s.EmailService.IsEnabled() {
		inviteURL := fmt.Sprintf("%s/auth/invite/server/%s", s.BaseURL, invite.Token)
		if err := s.sendInviteEmail(normalizedEmail, inviteURL, invite.ExpiresAt); err != nil {
			fmt.Printf("Warning: failed to send invite email to %s: %v\n", normalizedEmail, err)
		}
	}

	return invite, normalizedExpiration, nil
}

// VerifyInvite checks if an invite token is valid
func (s *AdminInviteService) VerifyInvite(token string) (*model.AdminInvite, error) {
	invite, err := s.InviteModel.GetInvite(token)
	if err != nil {
		return nil, fmt.Errorf("invalid invite token")
	}

	// Check if already used
	if invite.UsedBy != nil {
		return nil, fmt.Errorf("invite token has already been used")
	}

	// Check if expired
	if time.Now().After(invite.ExpiresAt) {
		return nil, fmt.Errorf("invite token has expired")
	}

	return invite, nil
}

// AcceptInvite processes an invite acceptance and creates the admin account
func (s *AdminInviteService) AcceptInvite(token, username, password string) (*model.Admin, error) {
	// Verify invite
	invite, err := s.VerifyInvite(token)
	if err != nil {
		return nil, err
	}

	normalizedUsername := util.NormalizeUsername(username)
	if err := util.ValidateUsername(normalizedUsername); err != nil {
		return nil, err
	}

	// Create admin account
	admin, err := s.AdminModel.Create(normalizedUsername, invite.InvitedEmail, password, false)
	if err != nil {
		return nil, fmt.Errorf("failed to create admin account: %w", err)
	}

	// Mark invite as used
	if err := s.InviteModel.MarkInviteUsed(token, admin.ID); err != nil {
		// Log error but don't fail (admin was created successfully)
		fmt.Printf("Warning: Failed to mark invite as used: %v\n", err)
	}

	return admin, nil
}

// GetPendingInvites returns all active invites
func (s *AdminInviteService) GetPendingInvites() ([]model.AdminInvite, error) {
	return s.InviteModel.GetPendingInvites()
}

// CleanupExpiredInvites removes expired invites (should be run periodically)
func (s *AdminInviteService) CleanupExpiredInvites() error {
	return s.InviteModel.DeleteExpiredInvites()
}

// sendInviteEmail sends an admin invitation email via the configured SMTP service.
func (s *AdminInviteService) sendInviteEmail(toEmail, inviteURL string, expiresAt time.Time) error {
	minutesRemaining := int(time.Until(expiresAt).Minutes())

	lang := "en"
	if inst := i18n.GetGlobalI18n(); inst != nil {
		if defaultLang := inst.GetDefaultLanguage(); defaultLang != "" {
			lang = defaultLang
		}
	}

	appName := translate("app.name", "Weather")

	subject, body, err := RenderEmailTemplate("user_invite", lang, map[string]any{
		"AppName":          appName,
		"InviteURL":        inviteURL,
		"MinutesRemaining": minutesRemaining,
		"ExpiresAt":        expiresAt.Format(time.RFC1123),
		"AppURL":           s.BaseURL,
	})
	if err != nil {
		return err
	}

	return s.EmailService.SendEmail(toEmail, subject, body)
}

// RevokeInvite revokes a pending invite
func (s *AdminInviteService) RevokeInvite(token string) error {
	// Mark as expired by setting used_at to now
	// This effectively invalidates the invite
	return s.InviteModel.MarkInviteUsed(token, 0)
}
