package service

import "strings"

// CreateFallbackLocation creates fallback coordinates for common cities
func CreateFallbackLocation(location string) *Coordinates {
	// Common fallback locations for major cities
	fallbacks := map[string]*Coordinates{
		"new york": {
			Latitude:    40.7128,
			Longitude:   -74.0060,
			Name:        "New York",
			Country:     "United States",
			CountryCode: "US",
			Timezone:    "America/New_York",
			Admin1:      "New York",
			Population:  8336817,
			FullName:    "New York, New York, United States",
			ShortName:   "New York, NY",
		},
		"london": {
			Latitude:    51.5074,
			Longitude:   -0.1278,
			Name:        "London",
			Country:     "United Kingdom",
			CountryCode: "GB",
			Timezone:    "Europe/London",
			Admin1:      "England",
			Population:  8982000,
			FullName:    "London, England, United Kingdom",
			ShortName:   "London, GB",
		},
		"paris": {
			Latitude:    48.8566,
			Longitude:   2.3522,
			Name:        "Paris",
			Country:     "France",
			CountryCode: "FR",
			Timezone:    "Europe/Paris",
			Admin1:      "Île-de-France",
			Population:  2165423,
			FullName:    "Paris, Île-de-France, France",
			ShortName:   "Paris, FR",
		},
		"tokyo": {
			Latitude:    35.6762,
			Longitude:   139.6503,
			Name:        "Tokyo",
			Country:     "Japan",
			CountryCode: "JP",
			Timezone:    "Asia/Tokyo",
			Admin1:      "Tokyo",
			Population:  13960000,
			FullName:    "Tokyo, Tokyo, Japan",
			ShortName:   "Tokyo, JP",
		},
		"sydney": {
			Latitude:    -33.8688,
			Longitude:   151.2093,
			Name:        "Sydney",
			Country:     "Australia",
			CountryCode: "AU",
			Timezone:    "Australia/Sydney",
			Admin1:      "New South Wales",
			Population:  5312000,
			FullName:    "Sydney, New South Wales, Australia",
			ShortName:   "Sydney, AU",
		},
		"los angeles": {
			Latitude:    34.0522,
			Longitude:   -118.2437,
			Name:        "Los Angeles",
			Country:     "United States",
			CountryCode: "US",
			Timezone:    "America/Los_Angeles",
			Admin1:      "California",
			Population:  3979576,
			FullName:    "Los Angeles, California, United States",
			ShortName:   "Los Angeles, CA",
		},
		"chicago": {
			Latitude:    41.8781,
			Longitude:   -87.6298,
			Name:        "Chicago",
			Country:     "United States",
			CountryCode: "US",
			Timezone:    "America/Chicago",
			Admin1:      "Illinois",
			Population:  2716000,
			FullName:    "Chicago, Illinois, United States",
			ShortName:   "Chicago, IL",
		},
		"toronto": {
			Latitude:    43.6532,
			Longitude:   -79.3832,
			Name:        "Toronto",
			Country:     "Canada",
			CountryCode: "CA",
			Timezone:    "America/Toronto",
			Admin1:      "Ontario",
			Population:  2731571,
			FullName:    "Toronto, Ontario, Canada",
			ShortName:   "Toronto, ON",
		},
		"berlin": {
			Latitude:    52.5200,
			Longitude:   13.4050,
			Name:        "Berlin",
			Country:     "Germany",
			CountryCode: "DE",
			Timezone:    "Europe/Berlin",
			Admin1:      "Berlin",
			Population:  3769495,
			FullName:    "Berlin, Berlin, Germany",
			ShortName:   "Berlin, DE",
		},
		"moscow": {
			Latitude:    55.7558,
			Longitude:   37.6173,
			Name:        "Moscow",
			Country:     "Russia",
			CountryCode: "RU",
			Timezone:    "Europe/Moscow",
			Admin1:      "Moscow",
			Population:  12500000,
			FullName:    "Moscow, Moscow, Russia",
			ShortName:   "Moscow, RU",
		},
		"beijing": {
			Latitude:    39.9042,
			Longitude:   116.4074,
			Name:        "Beijing",
			Country:     "China",
			CountryCode: "CN",
			Timezone:    "Asia/Shanghai",
			Admin1:      "Beijing",
			Population:  21540000,
			FullName:    "Beijing, Beijing, China",
			ShortName:   "Beijing, CN",
		},
		"shanghai": {
			Latitude:    31.2304,
			Longitude:   121.4737,
			Name:        "Shanghai",
			Country:     "China",
			CountryCode: "CN",
			Timezone:    "Asia/Shanghai",
			Admin1:      "Shanghai",
			Population:  24280000,
			FullName:    "Shanghai, Shanghai, China",
			ShortName:   "Shanghai, CN",
		},
		"mumbai": {
			Latitude:    19.0760,
			Longitude:   72.8777,
			Name:        "Mumbai",
			Country:     "India",
			CountryCode: "IN",
			Timezone:    "Asia/Kolkata",
			Admin1:      "Maharashtra",
			Population:  20411000,
			FullName:    "Mumbai, Maharashtra, India",
			ShortName:   "Mumbai, IN",
		},
		"dubai": {
			Latitude:    25.2048,
			Longitude:   55.2708,
			Name:        "Dubai",
			Country:     "United Arab Emirates",
			CountryCode: "AE",
			Timezone:    "Asia/Dubai",
			Admin1:      "Dubai",
			Population:  3331420,
			FullName:    "Dubai, Dubai, United Arab Emirates",
			ShortName:   "Dubai, AE",
		},
		"singapore": {
			Latitude:    1.3521,
			Longitude:   103.8198,
			Name:        "Singapore",
			Country:     "Singapore",
			CountryCode: "SG",
			Timezone:    "Asia/Singapore",
			Admin1:      "Central Singapore",
			Population:  5685800,
			FullName:    "Singapore, Central Singapore, Singapore",
			ShortName:   "Singapore, SG",
		},
		"san francisco": {
			Latitude:    37.7749,
			Longitude:   -122.4194,
			Name:        "San Francisco",
			Country:     "United States",
			CountryCode: "US",
			Timezone:    "America/Los_Angeles",
			Admin1:      "California",
			Population:  883305,
			FullName:    "San Francisco, California, United States",
			ShortName:   "San Francisco, CA",
		},
		"boston": {
			Latitude:    42.3601,
			Longitude:   -71.0589,
			Name:        "Boston",
			Country:     "United States",
			CountryCode: "US",
			Timezone:    "America/New_York",
			Admin1:      "Massachusetts",
			Population:  692600,
			FullName:    "Boston, Massachusetts, United States",
			ShortName:   "Boston, MA",
		},
		"seattle": {
			Latitude:    47.6062,
			Longitude:   -122.3321,
			Name:        "Seattle",
			Country:     "United States",
			CountryCode: "US",
			Timezone:    "America/Los_Angeles",
			Admin1:      "Washington",
			Population:  753675,
			FullName:    "Seattle, Washington, United States",
			ShortName:   "Seattle, WA",
		},
		"miami": {
			Latitude:    25.7617,
			Longitude:   -80.1918,
			Name:        "Miami",
			Country:     "United States",
			CountryCode: "US",
			Timezone:    "America/New_York",
			Admin1:      "Florida",
			Population:  467963,
			FullName:    "Miami, Florida, United States",
			ShortName:   "Miami, FL",
		},
		"dallas": {
			Latitude:    32.7767,
			Longitude:   -96.7970,
			Name:        "Dallas",
			Country:     "United States",
			CountryCode: "US",
			Timezone:    "America/Chicago",
			Admin1:      "Texas",
			Population:  1343573,
			FullName:    "Dallas, Texas, United States",
			ShortName:   "Dallas, TX",
		},
	}

	// Normalize location name for lookup
	normalized := strings.ToLower(strings.TrimSpace(location))

	// Empty/whitespace-only input never matches: without this guard,
	// strings.Contains(key, "") is always true, so the partial-match loop
	// below would return a nondeterministic city (depends on map
	// iteration order) instead of "no match".
	if normalized == "" {
		return nil
	}

	// Direct match
	if fallback, ok := fallbacks[normalized]; ok {
		return fallback
	}

	// Try partial matches
	for key, fallback := range fallbacks {
		if strings.Contains(normalized, key) || strings.Contains(key, normalized) {
			return fallback
		}
	}

	return nil
}
