package cli

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/webappsgo/wthr/src/common/dbtime"
	"github.com/webappsgo/wthr/src/common/display"
	"github.com/webappsgo/wthr/src/config"
	"github.com/webappsgo/wthr/src/database"
	"golang.org/x/crypto/argon2"
	_ "modernc.org/sqlite"
)

// BackupManifest represents metadata for a backup archive per AI.md PART 22
type BackupManifest struct {
	Version       string    `json:"version"`
	CreatedAt     time.Time `json:"created_at"`
	CreatedBy     string    `json:"created_by"`
	AppVersion    string    `json:"app_version"`
	ServerDB      bool      `json:"server_db"`
	UsersDB       bool      `json:"users_db"`
	ConfigFiles   bool      `json:"config_files"`
	LogsIncluded  bool      `json:"logs_included"`
	GeoIPIncluded bool      `json:"geoip_included"`
	Encrypted     bool      `json:"encrypted"`
	// "AES-256-GCM"
	EncryptionMethod string `json:"encryption_method,omitempty"`
	// sha256:...
	Checksum string `json:"checksum"`
}

// MaintenanceCommand handles maintenance operations per AI.md PART 22
func MaintenanceCommand(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("no maintenance command specified. Use: backup, restore, verify, admin-recovery")
	}

	cmd := args[0]
	remainingArgs := args[1:]

	switch cmd {
	case "backup":
		// Per AI.md PART 22 (Backup & Restore)
		return MaintenanceBackupCommand(remainingArgs)

	case "restore":
		// Per AI.md PART 22 (Backup & Restore)
		return MaintenanceRestoreCommand(remainingArgs)

	case "verify":
		// AI.md PART 22: Verify system integrity
		return verifySystem()

	case "admin-recovery", "setup":
		// AI.md PART 22: sole recovery path for a lost admin password/token
		return adminRecoverySetup()

	case "update":
		return updateServerConfig()

	case "mode":
		if len(remainingArgs) < 1 {
			return fmt.Errorf("mode requires a value: production or development")
		}
		return setMaintenanceMode(remainingArgs[0])

	default:
		return fmt.Errorf("unknown maintenance command: %s", cmd)
	}
}

func updateServerConfig() error {
	fmt.Println(T("cli.maintenance.updating_server_config"))
	fmt.Println(T("cli.maintenance.syncing_db_settings"))

	dataDir := os.Getenv("DATA_DIR")
	if dataDir == "" {
		dataDir = "/var/lib/webappsgo/wthr"
	}
	configDir := os.Getenv("CONFIG_DIR")
	if configDir == "" {
		configDir = "/etc/webappsgo/wthr"
	}

	serverDBPath := filepath.Join(dataDir, "db", "server.db")
	if _, err := os.Stat(serverDBPath); os.IsNotExist(err) {
		return fmt.Errorf("server database not found at %s", serverDBPath)
	}

	db, err := openDatabase(serverDBPath)
	if err != nil {
		return fmt.Errorf("failed to open database: %w", err)
	}
	defer db.Close()

	// server_config is the live settings table created by database.ServerSchema;
	// the legacy single-database "settings" table no longer exists.
	rows, err := database.QueryContext(context.Background(), db, database.TimeoutSimpleSelect, "SELECT key, value FROM server_config ORDER BY key")
	if err != nil {
		return fmt.Errorf("failed to read settings: %w", err)
	}
	defer rows.Close()

	// Build YAML lines grouped by first key segment
	sections := make(map[string][]string)
	order := []string{}
	for rows.Next() {
		var key, value string
		if err := rows.Scan(&key, &value); err != nil {
			continue
		}
		parts := splitKey(key)
		section := parts[0]
		if _, exists := sections[section]; !exists {
			order = append(order, section)
		}
		sections[section] = append(sections[section], fmt.Sprintf("  %s: %s", key, yamlQuote(value)))
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("error reading settings: %w", err)
	}

	var yaml strings.Builder
	yaml.WriteString("# wthr server configuration — auto-generated by 'wthr maintenance update'\n")
	yaml.WriteString("# Edit with care; restart or send SIGHUP to apply changes.\n\n")
	for _, section := range order {
		yaml.WriteString(section + ":\n")
		for _, line := range sections[section] {
			yaml.WriteString(line + "\n")
		}
		yaml.WriteString("\n")
	}

	configPath := filepath.Join(configDir, "server.yml")
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}
	if err := os.WriteFile(configPath, []byte(yaml.String()), 0640); err != nil {
		return fmt.Errorf("failed to write %s: %w", configPath, err)
	}

	fmt.Printf("\n"+T("cli.maintenance.config_written")+"\n", display.Emoji("✓", "[OK]"), configPath)
	fmt.Println(T("cli.maintenance.sighup_hint"))
	return nil
}

// splitKey splits "section.sub.key" and returns ["section", "sub", "key"]
func splitKey(key string) []string {
	var parts []string
	start := 0
	for i, c := range key {
		if c == '.' {
			parts = append(parts, key[start:i])
			start = i + 1
		}
	}
	parts = append(parts, key[start:])
	return parts
}

// yamlQuote wraps a value in double-quotes when it contains special YAML characters.
func yamlQuote(v string) string {
	for _, c := range v {
		if c == ':' || c == '#' || c == '"' || c == '\'' || c == '\n' || c == '{' || c == '}' || c == '[' || c == ']' {
			return fmt.Sprintf("%q", v)
		}
	}
	return v
}

// setMaintenanceMode sets the application mode by rewriting the MODE line in server.yml.
func setMaintenanceMode(mode string) error {
	switch mode {
	case "prod", "production":
		mode = "production"
	case "dev", "development":
		mode = "development"
	default:
		return fmt.Errorf("invalid mode: %s (use production or development)", mode)
	}

	fmt.Printf(T("cli.maintenance.setting_mode")+"\n", mode)

	configDir := os.Getenv("CONFIG_DIR")
	if configDir == "" {
		configDir = "/etc/webappsgo/wthr"
	}
	configPath := filepath.Join(configDir, "server.yml")

	var existing []byte
	if data, err := os.ReadFile(configPath); err == nil {
		existing = data
	}

	// Rewrite or append the server.mode line
	updated := updateYAMLKey(string(existing), "server.mode", mode)

	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}
	if err := os.WriteFile(configPath, []byte(updated), 0640); err != nil {
		return fmt.Errorf("failed to write %s: %w", configPath, err)
	}

	fmt.Printf("\n"+T("cli.maintenance.mode_set")+"\n", display.Emoji("✓", "[OK]"), mode, configPath)
	fmt.Println(T("cli.maintenance.restart_hint"))
	return nil
}

// updateYAMLKey updates a dotted key (e.g. "server.mode") in a YAML string,
// replacing the existing line or appending under the correct section.
func updateYAMLKey(yaml, key, value string) string {
	parts := splitKey(key)
	if len(parts) < 2 {
		return yaml
	}
	section := parts[0]
	subKey := strings.Join(parts[1:], ".")
	newLine := fmt.Sprintf("  %s: %s", subKey, yamlQuote(value))

	lines := strings.Split(yaml, "\n")
	inSection := false
	replaced := false
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, section+":") && !strings.HasPrefix(line, " ") {
			inSection = true
			continue
		}
		if inSection && !strings.HasPrefix(line, " ") && trimmed != "" {
			inSection = false
		}
		if inSection && strings.HasPrefix(strings.TrimSpace(line), subKey+":") {
			lines[i] = newLine
			replaced = true
		}
	}

	if replaced {
		return strings.Join(lines, "\n")
	}

	// Section or key not found — append
	var out strings.Builder
	out.WriteString(strings.TrimRight(yaml, "\n"))
	out.WriteString("\n\n" + section + ":\n" + newLine + "\n")
	return out.String()
}

// adminRecoverySetup allows recovery of admin access after restore or lockout
func adminRecoverySetup() error {
	fmt.Printf(T("cli.maintenance.admin_recovery_title")+"\n", display.Emoji("🔧", "*"))
	fmt.Println(T("cli.maintenance.admin_recovery_description"))
	fmt.Println()

	// Get directory paths
	dataDir := os.Getenv("DATA_DIR")
	if dataDir == "" {
		dataDir = "/var/lib/webappsgo/wthr"
	}

	// Connect to server.db
	serverDBPath := filepath.Join(dataDir, "db", "server.db")

	// Check if database exists
	if _, err := os.Stat(serverDBPath); os.IsNotExist(err) {
		return fmt.Errorf("server database not found at %s", serverDBPath)
	}

	// Import database package is already imported via database initialization
	// We'll use direct SQL connection for CLI tool
	db, err := openDatabase(serverDBPath)
	if err != nil {
		return fmt.Errorf("failed to open database: %w", err)
	}
	defer db.Close()

	// Prompt for new admin credentials
	fmt.Print(T("cli.maintenance.prompt_username"))
	var username string
	fmt.Scanln(&username)
	if username == "" {
		username = "admin"
	}

	fmt.Print(T("cli.maintenance.prompt_password"))
	var password string
	fmt.Scanln(&password)
	if password == "" {
		return fmt.Errorf("password cannot be empty")
	}

	fmt.Print(T("cli.maintenance.prompt_confirm_password"))
	var confirmPassword string
	fmt.Scanln(&confirmPassword)
	if password != confirmPassword {
		return fmt.Errorf("passwords do not match")
	}

	// Hash password with Argon2id (AI.md PART 3 requirement)
	passwordHash, err := hashPasswordArgon2id(password)
	if err != nil {
		return fmt.Errorf("failed to hash password: %w", err)
	}

	// Timestamps are bound as canonical UTC text so the value matches what
	// CURRENT_TIMESTAMP writes and stays portable across SQLite, PostgreSQL and
	// MySQL — a bound time.Time would be serialized in the host's local zone.
	now := dbtime.FormatSQLTimestamp(time.Now())

	// Update or create admin account in server_admin_credentials, the live table
	// created by database.ServerSchema. The legacy "admin_credentials" table
	// belonged to the removed single-database schema and no longer exists.
	// First, try to update existing admin
	result, err := database.ExecContext(context.Background(), db, database.TimeoutWrite, `
		UPDATE server_admin_credentials
		SET username = ?, password_hash = ?, updated_at = ?
		WHERE id = 1
	`, username, passwordHash, now)

	if err != nil {
		return fmt.Errorf("failed to update admin credentials: %w", err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("failed to check update result: %w", err)
	}

	// If no rows updated, insert new admin
	if rowsAffected == 0 {
		// server_admin_credentials.email is NOT NULL UNIQUE, so a recovery insert
		// must supply one; the setup wizard lets the admin change it afterwards.
		email := config.DefaultEmailAddress(username, config.GetGlobalConfig())

		_, err = database.ExecContext(context.Background(), db, database.TimeoutWrite, `
			INSERT INTO server_admin_credentials (id, username, email, password_hash, is_super_admin, is_active, created_at, updated_at)
			VALUES (1, ?, ?, ?, 1, 1, ?, ?)
		`, username, email, passwordHash, now, now)

		if err != nil {
			return fmt.Errorf("failed to create admin credentials: %w", err)
		}
		fmt.Printf("\n"+T("cli.maintenance.admin_created")+"\n", display.Emoji("✓", "[OK]"))
	} else {
		fmt.Printf("\n"+T("cli.maintenance.admin_updated")+"\n", display.Emoji("✓", "[OK]"))
	}

	fmt.Printf(T("cli.maintenance.username_line")+"\n", username)
	fmt.Printf("\n"+T("cli.maintenance.restart_login_warning")+"\n", display.Emoji("⚠️", "WARNING:"))
	fmt.Println(T("cli.maintenance.systemctl_restart_hint"))

	return nil
}

// openDatabase opens a SQLite database connection
func openDatabase(dbPath string) (*sql.DB, error) {
	// Driver name must be "sqlite" (modernc.org/sqlite, the mandated CGO-free
	// driver per AI.md PART 3) — "sqlite3" is only registered by the CGO
	// mattn/go-sqlite3 driver, which this project never imports.
	db, err := sql.Open("sqlite", dbPath)
	if err != nil {
		return nil, err
	}

	// Test connection with a timeout per AI.md PART 10 (Query Timeouts)
	if err := database.PingWithTimeout(db); err != nil {
		db.Close()
		return nil, err
	}

	return db, nil
}

// hashPasswordArgon2id hashes a password using Argon2id
// AI.md PART 3: Argon2id parameters (time=3, memory=64*1024, threads=4, keyLen=32)
func hashPasswordArgon2id(password string) (string, error) {
	// Generate random salt (16 bytes)
	salt := make([]byte, 16)
	if _, err := rand.Read(salt); err != nil {
		return "", fmt.Errorf("failed to generate salt: %w", err)
	}

	// Argon2id parameters from AI.md PART 3
	const (
		time = 3
		// 64 MB
		memory  = 64 * 1024
		threads = 4
		keyLen  = 32
	)

	// Generate hash
	hash := argon2.IDKey([]byte(password), salt, time, memory, threads, keyLen)

	// Encode as: $argon2id$v=19$m=65536,t=3,p=4$<salt>$<hash>
	b64Salt := base64.RawStdEncoding.EncodeToString(salt)
	b64Hash := base64.RawStdEncoding.EncodeToString(hash)

	return fmt.Sprintf("$argon2id$v=19$m=%d,t=%d,p=%d$%s$%s",
		memory, time, threads, b64Salt, b64Hash), nil
}

// verifySystem verifies system integrity per AI.md PART 22
func verifySystem() error {
	fmt.Printf(T("cli.maintenance.verify_title")+"\n", display.Emoji("🔍", "[..]"))
	fmt.Println()

	// Get directory paths
	dataDir := os.Getenv("DATA_DIR")
	configDir := os.Getenv("CONFIG_DIR")
	logDir := os.Getenv("LOG_DIR")

	// Default paths if not set
	if dataDir == "" {
		dataDir = "/var/lib/webappsgo/wthr"
	}
	if configDir == "" {
		configDir = "/etc/webappsgo/wthr"
	}
	if logDir == "" {
		logDir = "/var/log/webappsgo/wthr"
	}

	errors := 0

	// 1. Verify server.db exists and is accessible
	fmt.Print(T("cli.maintenance.checking_server_db"))
	serverDBPath := filepath.Join(dataDir, "db", "server.db")
	if err := verifyDatabaseFile(serverDBPath); err != nil {
		fmt.Printf(T("cli.maintenance.check_fail")+"\n", display.Emoji("❌", "[FAIL]"), err)
		errors++
	} else {
		fmt.Printf(T("cli.maintenance.check_ok")+"\n", display.Emoji("✓", "[OK]"))
	}

	// 2. Verify users.db exists and is accessible
	fmt.Print(T("cli.maintenance.checking_users_db"))
	usersDBPath := filepath.Join(dataDir, "db", "users.db")
	if err := verifyDatabaseFile(usersDBPath); err != nil {
		fmt.Printf(T("cli.maintenance.check_fail")+"\n", display.Emoji("❌", "[FAIL]"), err)
		errors++
	} else {
		fmt.Printf(T("cli.maintenance.check_ok")+"\n", display.Emoji("✓", "[OK]"))
	}

	// 3. Verify server.yml exists
	fmt.Print(T("cli.maintenance.checking_server_yml"))
	configPath := filepath.Join(configDir, "server.yml")
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		fmt.Printf(T("cli.maintenance.config_not_found")+"\n", display.Emoji("⚠️", "WARNING:"))
	} else if err != nil {
		fmt.Printf(T("cli.maintenance.check_fail")+"\n", display.Emoji("❌", "[FAIL]"), err)
		errors++
	} else {
		fmt.Printf(T("cli.maintenance.check_ok")+"\n", display.Emoji("✓", "[OK]"))
	}

	// 4. Verify log directory is writable
	fmt.Print(T("cli.maintenance.checking_log_dir"))
	if err := verifyDirectoryWritable(logDir); err != nil {
		fmt.Printf(T("cli.maintenance.check_fail")+"\n", display.Emoji("❌", "[FAIL]"), err)
		errors++
	} else {
		fmt.Printf(T("cli.maintenance.check_ok")+"\n", display.Emoji("✓", "[OK]"))
	}

	// 5. Verify data directory is writable
	fmt.Print(T("cli.maintenance.checking_data_dir"))
	if err := verifyDirectoryWritable(dataDir); err != nil {
		fmt.Printf(T("cli.maintenance.check_fail")+"\n", display.Emoji("❌", "[FAIL]"), err)
		errors++
	} else {
		fmt.Printf(T("cli.maintenance.check_ok")+"\n", display.Emoji("✓", "[OK]"))
	}

	// 6. Verify at least one admin account exists
	fmt.Print(T("cli.maintenance.checking_admin_accounts"))
	if err := verifyAdminExists(serverDBPath); err != nil {
		fmt.Printf(T("cli.maintenance.admin_check_warning")+"\n", display.Emoji("⚠️", "[!]"), err)
		fmt.Println(T("cli.maintenance.admin_recovery_run_hint"))
	} else {
		fmt.Printf(T("cli.maintenance.check_ok")+"\n", display.Emoji("✓", "[OK]"))
	}

	// 7. Check GeoIP databases (optional)
	fmt.Print(T("cli.maintenance.checking_geoip"))
	geoipDir := filepath.Join(dataDir, "geoip")
	if _, err := os.Stat(geoipDir); os.IsNotExist(err) {
		fmt.Printf(T("cli.maintenance.geoip_not_found")+"\n", display.Emoji("⚠️", "WARNING:"))
	} else {
		fmt.Printf(T("cli.maintenance.check_ok")+"\n", display.Emoji("✓", "[OK]"))
	}

	// Summary
	fmt.Println()
	if errors == 0 {
		fmt.Printf(T("cli.maintenance.verify_success")+"\n", display.Emoji("✓", "[OK]"))
		return nil
	}

	fmt.Printf(T("cli.maintenance.verify_failed")+"\n", display.Emoji("❌", "[FAIL]"), errors)
	return fmt.Errorf("verification failed")
}

// verifyDatabaseFile verifies a database file exists and is accessible
func verifyDatabaseFile(dbPath string) error {
	// Check if file exists
	info, err := os.Stat(dbPath)
	if os.IsNotExist(err) {
		return fmt.Errorf("database not found")
	}
	if err != nil {
		return fmt.Errorf("cannot access: %w", err)
	}

	// Check if it's a regular file
	if !info.Mode().IsRegular() {
		return fmt.Errorf("not a regular file")
	}

	// Try to open it
	db, err := sql.Open("sqlite", dbPath)
	if err != nil {
		return fmt.Errorf("cannot open: %w", err)
	}
	defer db.Close()

	// Try to ping, with a timeout per AI.md PART 10 (Query Timeouts)
	if err := database.PingWithTimeout(db); err != nil {
		return fmt.Errorf("database corrupted: %w", err)
	}

	return nil
}

// verifyDirectoryWritable verifies a directory exists and is writable
func verifyDirectoryWritable(dirPath string) error {
	// Check if directory exists
	info, err := os.Stat(dirPath)
	if os.IsNotExist(err) {
		// Try to create it
		if err := os.MkdirAll(dirPath, 0755); err != nil {
			return fmt.Errorf("cannot create: %w", err)
		}
		return nil
	}
	if err != nil {
		return fmt.Errorf("cannot access: %w", err)
	}

	// Check if it's a directory
	if !info.IsDir() {
		return fmt.Errorf("not a directory")
	}

	// Try to create a test file
	testFile := filepath.Join(dirPath, ".write-test")
	if err := os.WriteFile(testFile, []byte("test"), 0644); err != nil {
		return fmt.Errorf("not writable: %w", err)
	}

	// Clean up test file
	os.Remove(testFile)

	return nil
}

// verifyAdminExists checks if at least one admin account exists
func verifyAdminExists(serverDBPath string) error {
	db, err := sql.Open("sqlite", serverDBPath)
	if err != nil {
		return fmt.Errorf("cannot open database: %w", err)
	}
	defer db.Close()

	var count int
	err = database.QueryRowContext(context.Background(), db, database.TimeoutSimpleSelect, "SELECT COUNT(*) FROM server_admin_credentials").Scan(&count)
	if err != nil {
		return fmt.Errorf("cannot query: %w", err)
	}

	if count == 0 {
		return fmt.Errorf("no admin accounts found")
	}

	return nil
}
