// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"
)

type AccountSettings struct {
	DisplayName string `json:"displayName"`
	Bio         string `json:"bio"`
	Location    string `json:"location"`
	Website     string `json:"website"`
	Timezone    string `json:"timezone"`
	Language    string `json:"language"`
	DateFormat  string `json:"dateFormat"`
	TimeFormat  string `json:"timeFormat"`
}

type AccountSettingsInput struct {
	DisplayName string `json:"displayName"`
	Bio         string `json:"bio"`
	Location    string `json:"location"`
	Website     string `json:"website"`
	Timezone    string `json:"timezone"`
	Language    string `json:"language"`
	DateFormat  string `json:"dateFormat"`
	TimeFormat  string `json:"timeFormat"`
}

type AppearanceSettings struct {
	Theme        string `json:"theme"`
	FontSize     string `json:"fontSize"`
	ReduceMotion bool   `json:"reduceMotion"`
}

type AppearanceSettingsInput struct {
	Theme        string `json:"theme"`
	FontSize     string `json:"fontSize"`
	ReduceMotion bool   `json:"reduceMotion"`
}

type Astronomy struct {
	Sunrise          *string `json:"sunrise,omitempty"`
	Sunset           *string `json:"sunset,omitempty"`
	Moonrise         *string `json:"moonrise,omitempty"`
	Moonset          *string `json:"moonset,omitempty"`
	MoonPhase        *string `json:"moonPhase,omitempty"`
	MoonIllumination *int    `json:"moonIllumination,omitempty"`
}

type AuditLog struct {
	ID        string    `json:"id"`
	UserID    *int      `json:"userId,omitempty"`
	Action    string    `json:"action"`
	Resource  *string   `json:"resource,omitempty"`
	Details   *string   `json:"details,omitempty"`
	IP        *string   `json:"ip,omitempty"`
	UserAgent *string   `json:"userAgent,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
}

type BulkResponse struct {
	Ok      bool   `json:"ok"`
	Message string `json:"message"`
	Updated *int   `json:"updated,omitempty"`
	Failed  *int   `json:"failed,omitempty"`
}

type ChannelStats struct {
	Sent     int        `json:"sent"`
	Failed   int        `json:"failed"`
	LastSent *time.Time `json:"lastSent,omitempty"`
}

type ContactSubmission struct {
	Ok      bool   `json:"ok"`
	Message string `json:"message"`
}

type CoordinatesLookup struct {
	Lat      float64 `json:"lat"`
	Lon      float64 `json:"lon"`
	City     *string `json:"city,omitempty"`
	Region   *string `json:"region,omitempty"`
	Country  string  `json:"country"`
	Timezone *string `json:"timezone,omitempty"`
}

type CurrentWeather struct {
	Temperature   float64           `json:"temperature"`
	FeelsLike     *float64          `json:"feelsLike,omitempty"`
	Humidity      int               `json:"humidity"`
	Pressure      *float64          `json:"pressure,omitempty"`
	WindSpeed     float64           `json:"windSpeed"`
	WindDirection *string           `json:"windDirection,omitempty"`
	Precipitation *float64          `json:"precipitation,omitempty"`
	CloudCover    *int              `json:"cloudCover,omitempty"`
	Visibility    *float64          `json:"visibility,omitempty"`
	UvIndex       *float64          `json:"uvIndex,omitempty"`
	Condition     *WeatherCondition `json:"condition"`
	LastUpdated   time.Time         `json:"lastUpdated"`
}

type DatabaseHealth struct {
	Status  string  `json:"status"`
	Latency *int    `json:"latency,omitempty"`
	Error   *string `json:"error,omitempty"`
}

type DatabaseStats struct {
	Size        float64 `json:"size"`
	Tables      *int    `json:"tables,omitempty"`
	Connections *int    `json:"connections,omitempty"`
}

type DayForecast struct {
	MaxTemp            float64           `json:"maxTemp"`
	MinTemp            float64           `json:"minTemp"`
	AvgTemp            *float64          `json:"avgTemp,omitempty"`
	MaxWind            *float64          `json:"maxWind,omitempty"`
	TotalPrecipitation *float64          `json:"totalPrecipitation,omitempty"`
	AvgHumidity        *float64          `json:"avgHumidity,omitempty"`
	Condition          *WeatherCondition `json:"condition"`
	ChanceOfRain       *int              `json:"chanceOfRain,omitempty"`
	ChanceOfSnow       *int              `json:"chanceOfSnow,omitempty"`
}

type DiskHealth struct {
	Used       float64 `json:"used"`
	Total      float64 `json:"total"`
	Percentage float64 `json:"percentage"`
}

type Earthquake struct {
	ID        string    `json:"id"`
	Magnitude float64   `json:"magnitude"`
	Location  string    `json:"location"`
	Depth     *float64  `json:"depth,omitempty"`
	Time      time.Time `json:"time"`
	Lat       float64   `json:"lat"`
	Lon       float64   `json:"lon"`
	Tsunami   *bool     `json:"tsunami,omitempty"`
	URL       *string   `json:"url,omitempty"`
}

type ForecastDay struct {
	Date  string          `json:"date"`
	Day   *DayForecast    `json:"day"`
	Hour  []*HourForecast `json:"hour,omitempty"`
	Astro *Astronomy      `json:"astro,omitempty"`
}

type HealthStatus struct {
	Status            string                   `json:"status"`
	Message           *string                  `json:"message,omitempty"`
	Database          *DatabaseHealth          `json:"database,omitempty"`
	Memory            *MemoryHealth            `json:"memory,omitempty"`
	Disk              *DiskHealth              `json:"disk,omitempty"`
	Ssl               *SSLHealth               `json:"ssl,omitempty"`
	Scheduler         *SchedulerHealth         `json:"scheduler,omitempty"`
	Sessions          *SessionsHealth          `json:"sessions,omitempty"`
	Requests          *RequestsHealth          `json:"requests,omitempty"`
	LocationDatabases *LocationDatabasesHealth `json:"locationDatabases,omitempty"`
	Uptime            string                   `json:"uptime"`
	Timestamp         time.Time                `json:"timestamp"`
}

type HistoricalWeather struct {
	Location *Location       `json:"location"`
	Date     string          `json:"date"`
	Day      *DayForecast    `json:"day"`
	Hour     []*HourForecast `json:"hour,omitempty"`
	Astro    *Astronomy      `json:"astro,omitempty"`
}

type HourForecast struct {
	Time          string            `json:"time"`
	Temperature   float64           `json:"temperature"`
	FeelsLike     *float64          `json:"feelsLike,omitempty"`
	Humidity      *int              `json:"humidity,omitempty"`
	WindSpeed     *float64          `json:"windSpeed,omitempty"`
	WindDirection *string           `json:"windDirection,omitempty"`
	Precipitation *float64          `json:"precipitation,omitempty"`
	ChanceOfRain  *int              `json:"chanceOfRain,omitempty"`
	ChanceOfSnow  *int              `json:"chanceOfSnow,omitempty"`
	Condition     *WeatherCondition `json:"condition"`
}

type Hurricane struct {
	ID           string               `json:"id"`
	Name         string               `json:"name"`
	Category     int                  `json:"category"`
	MaxWindSpeed float64              `json:"maxWindSpeed"`
	MinPressure  *float64             `json:"minPressure,omitempty"`
	Location     *Location            `json:"location"`
	Status       string               `json:"status"`
	Movement     *HurricaneMovement   `json:"movement,omitempty"`
	Forecast     []*HurricaneForecast `json:"forecast,omitempty"`
	LastUpdated  time.Time            `json:"lastUpdated"`
}

type HurricaneForecast struct {
	Time         time.Time `json:"time"`
	Lat          float64   `json:"lat"`
	Lon          float64   `json:"lon"`
	MaxWindSpeed *float64  `json:"maxWindSpeed,omitempty"`
	Category     *int      `json:"category,omitempty"`
}

type HurricaneMovement struct {
	Direction *string  `json:"direction,omitempty"`
	Speed     *float64 `json:"speed,omitempty"`
}

type IPGeolocation struct {
	IP          string  `json:"ip"`
	City        *string `json:"city,omitempty"`
	Region      *string `json:"region,omitempty"`
	Country     string  `json:"country"`
	CountryCode string  `json:"countryCode"`
	Lat         float64 `json:"lat"`
	Lon         float64 `json:"lon"`
	Timezone    *string `json:"timezone,omitempty"`
	Isp         *string `json:"isp,omitempty"`
	Org         *string `json:"org,omitempty"`
}

type Location struct {
	Name      string  `json:"name"`
	Region    *string `json:"region,omitempty"`
	Country   string  `json:"country"`
	Lat       float64 `json:"lat"`
	Lon       float64 `json:"lon"`
	Timezone  *string `json:"timezone,omitempty"`
	Localtime *string `json:"localtime,omitempty"`
}

type LocationDBStatus struct {
	Loaded      bool       `json:"loaded"`
	Count       *int       `json:"count,omitempty"`
	LastUpdated *time.Time `json:"lastUpdated,omitempty"`
}

type LocationDatabasesHealth struct {
	Countries *LocationDBStatus `json:"countries,omitempty"`
	Cities    *LocationDBStatus `json:"cities,omitempty"`
	Zipcodes  *LocationDBStatus `json:"zipcodes,omitempty"`
	Geoip     *LocationDBStatus `json:"geoip,omitempty"`
}

type LocationSearchResult struct {
	ID      *int    `json:"id,omitempty"`
	Name    string  `json:"name"`
	Region  *string `json:"region,omitempty"`
	Country string  `json:"country"`
	Lat     float64 `json:"lat"`
	Lon     float64 `json:"lon"`
	URL     *string `json:"url,omitempty"`
}

type LocationStats struct {
	Total   int      `json:"total"`
	PerUser *float64 `json:"perUser,omitempty"`
}

type MemoryHealth struct {
	Used       float64 `json:"used"`
	Total      float64 `json:"total"`
	Percentage float64 `json:"percentage"`
}

type MoonPhase struct {
	Phase        string     `json:"phase"`
	Illumination float64    `json:"illumination"`
	Age          *float64   `json:"age,omitempty"`
	Distance     *float64   `json:"distance,omitempty"`
	Angle        *float64   `json:"angle,omitempty"`
	Moonrise     *string    `json:"moonrise,omitempty"`
	Moonset      *string    `json:"moonset,omitempty"`
	NextFullMoon *time.Time `json:"nextFullMoon,omitempty"`
	NextNewMoon  *time.Time `json:"nextNewMoon,omitempty"`
}

type Mutation struct {
}

type NotificationChannel struct {
	Type    string        `json:"type"`
	Enabled bool          `json:"enabled"`
	Config  any           `json:"config,omitempty"`
	Stats   *ChannelStats `json:"stats,omitempty"`
}

type NotificationSettings struct {
	EmailSecurity bool   `json:"emailSecurity"`
	EmailMentions bool   `json:"emailMentions"`
	EmailUpdates  bool   `json:"emailUpdates"`
	EmailDigest   string `json:"emailDigest"`
	PushEnabled   bool   `json:"pushEnabled"`
	PushMentions  bool   `json:"pushMentions"`
}

type NotificationSettingsInput struct {
	EmailSecurity bool   `json:"emailSecurity"`
	EmailMentions bool   `json:"emailMentions"`
	EmailUpdates  bool   `json:"emailUpdates"`
	EmailDigest   string `json:"emailDigest"`
	PushEnabled   bool   `json:"pushEnabled"`
	PushMentions  bool   `json:"pushMentions"`
}

type NotificationStats struct {
	Total  int  `json:"total"`
	Unread *int `json:"unread,omitempty"`
}

type PrivacySettings struct {
	Visibility    string `json:"visibility"`
	ShowEmail     bool   `json:"showEmail"`
	ShowActivity  bool   `json:"showActivity"`
	ShowOrgs      bool   `json:"showOrgs"`
	Searchable    bool   `json:"searchable"`
	OrgVisibility bool   `json:"orgVisibility"`
}

type PrivacySettingsInput struct {
	Visibility    string `json:"visibility"`
	ShowEmail     bool   `json:"showEmail"`
	ShowActivity  bool   `json:"showActivity"`
	ShowOrgs      bool   `json:"showOrgs"`
	Searchable    bool   `json:"searchable"`
	OrgVisibility bool   `json:"orgVisibility"`
}

type PublicAvatar struct {
	Type string `json:"type"`
	Urls any    `json:"urls"`
}

type PublicUserProfile struct {
	Username    string        `json:"username"`
	DisplayName *string       `json:"displayName,omitempty"`
	Avatar      *PublicAvatar `json:"avatar"`
	Bio         *string       `json:"bio,omitempty"`
	Location    *string       `json:"location,omitempty"`
	Website     *string       `json:"website,omitempty"`
	Verified    bool          `json:"verified"`
	CreatedAt   time.Time     `json:"createdAt"`
}

type Query struct {
}

type QueueStats struct {
	Pending    int `json:"pending"`
	Processing int `json:"processing"`
	Completed  int `json:"completed"`
	Failed     int `json:"failed"`
}

type RequestStats struct {
	Total     int      `json:"total"`
	PerSecond *float64 `json:"perSecond,omitempty"`
	Errors    *int     `json:"errors,omitempty"`
}

type RequestsHealth struct {
	Total     int      `json:"total"`
	PerSecond *float64 `json:"perSecond,omitempty"`
}

type SMTPProvider struct {
	Name   string `json:"name"`
	Host   string `json:"host"`
	Port   int    `json:"port"`
	Secure bool   `json:"secure"`
}

type SSLHealth struct {
	Enabled       bool       `json:"enabled"`
	ExpiresAt     *time.Time `json:"expiresAt,omitempty"`
	DaysRemaining *int       `json:"daysRemaining,omitempty"`
}

type ScheduledTask struct {
	Name        string     `json:"name"`
	Schedule    string     `json:"schedule"`
	Enabled     bool       `json:"enabled"`
	LastRun     *time.Time `json:"lastRun,omitempty"`
	NextRun     *time.Time `json:"nextRun,omitempty"`
	RunCount    int        `json:"runCount"`
	ErrorCount  int        `json:"errorCount"`
	AvgDuration *float64   `json:"avgDuration,omitempty"`
}

type SchedulerHealth struct {
	Running bool       `json:"running"`
	Tasks   *int       `json:"tasks,omitempty"`
	LastRun *time.Time `json:"lastRun,omitempty"`
}

type ServerAdmin struct {
	ID           string     `json:"id"`
	Username     string     `json:"username"`
	Email        string     `json:"email"`
	IsSuperAdmin bool       `json:"isSuperAdmin"`
	IsActive     bool       `json:"isActive"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	LastLoginAt  *time.Time `json:"lastLoginAt,omitempty"`
}

type ServerAdminInvite struct {
	Token     string    `json:"token"`
	Email     string    `json:"email"`
	ExpiresAt time.Time `json:"expiresAt"`
	ExpiresIn string    `json:"expiresIn"`
	InviteURL string    `json:"inviteUrl"`
}

type ServerAdminOverview struct {
	Count         int          `json:"count"`
	CurrentAdmin  *ServerAdmin `json:"currentAdmin"`
	OnlineAdmins  []string     `json:"onlineAdmins"`
	PrivacyNotice string       `json:"privacyNotice"`
}

type SessionsHealth struct {
	Active int `json:"active"`
	Total  int `json:"total"`
}

type SettingInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SevereWeather struct {
	ID          string    `json:"id"`
	Type        string    `json:"type"`
	Severity    string    `json:"severity"`
	Location    *Location `json:"location"`
	Effective   time.Time `json:"effective"`
	Expires     time.Time `json:"expires"`
	Description string    `json:"description"`
	Instruction *string   `json:"instruction,omitempty"`
}

type SystemStats struct {
	Uptime        string             `json:"uptime"`
	Requests      *RequestStats      `json:"requests"`
	Users         *UserStats         `json:"users"`
	Locations     *LocationStats     `json:"locations"`
	Notifications *NotificationStats `json:"notifications"`
	Database      *DatabaseStats     `json:"database"`
}

type TaskHistory struct {
	TaskName    string     `json:"taskName"`
	StartedAt   time.Time  `json:"startedAt"`
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	Duration    *float64   `json:"duration,omitempty"`
	Ok          bool       `json:"ok"`
	Error       *string    `json:"error,omitempty"`
}

type UnreadCount struct {
	Count int `json:"count"`
}

type UserInvite struct {
	ID        string     `json:"id"`
	Token     string     `json:"token"`
	Username  string     `json:"username"`
	Email     string     `json:"email"`
	Role      string     `json:"role"`
	CreatedAt time.Time  `json:"createdAt"`
	ExpiresAt time.Time  `json:"expiresAt"`
	MaxUses   int        `json:"maxUses"`
	UseCount  int        `json:"useCount"`
	UsedAt    *time.Time `json:"usedAt,omitempty"`
	Status    string     `json:"status"`
	InviteURL string     `json:"inviteUrl"`
}

type UserSettings struct {
	Account       *AccountSettings      `json:"account"`
	Privacy       *PrivacySettings      `json:"privacy"`
	Notifications *NotificationSettings `json:"notifications"`
	Appearance    *AppearanceSettings   `json:"appearance"`
}

type UserStats struct {
	Total  int  `json:"total"`
	Active *int `json:"active,omitempty"`
	Admins *int `json:"admins,omitempty"`
}

type UserToken struct {
	ID          string     `json:"id"`
	Name        *string    `json:"name,omitempty"`
	TokenPrefix string     `json:"tokenPrefix"`
	Scopes      *string    `json:"scopes,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	ExpiresAt   *time.Time `json:"expiresAt,omitempty"`
	LastUsedAt  *time.Time `json:"lastUsedAt,omitempty"`
	Token       *string    `json:"token,omitempty"`
}

type Weather struct {
	Location  *Location       `json:"location"`
	Current   *CurrentWeather `json:"current"`
	Forecast  []*ForecastDay  `json:"forecast,omitempty"`
	Alerts    []*WeatherAlert `json:"alerts,omitempty"`
	Astronomy *Astronomy      `json:"astronomy,omitempty"`
	Timestamp time.Time       `json:"timestamp"`
}

type WeatherAlert struct {
	Headline    string     `json:"headline"`
	Severity    string     `json:"severity"`
	Urgency     *string    `json:"urgency,omitempty"`
	Areas       *string    `json:"areas,omitempty"`
	Category    *string    `json:"category,omitempty"`
	Event       string     `json:"event"`
	Effective   *time.Time `json:"effective,omitempty"`
	Expires     *time.Time `json:"expires,omitempty"`
	Description string     `json:"description"`
	Instruction *string    `json:"instruction,omitempty"`
}

type WeatherCondition struct {
	Text string  `json:"text"`
	Icon *string `json:"icon,omitempty"`
	Code *int    `json:"code,omitempty"`
}

type ZipCodeLookup struct {
	ZipCode string  `json:"zipCode"`
	City    string  `json:"city"`
	State   string  `json:"state"`
	Country string  `json:"country"`
	Lat     float64 `json:"lat"`
	Lon     float64 `json:"lon"`
}
