package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.60

import (
	"context"

	"github.com/99designs/gqlgen/graphql/introspection"
)

// IsDeprecated is the resolver for the isDeprecated field.
func (r *inputValueResolverImpl) IsDeprecated(ctx context.Context, obj *introspection.InputValue) (bool, error) {
	// InputValue doesn't have deprecation in gqlgen introspection
	return false, nil
}

// DeprecationReason is the resolver for the deprecationReason field.
func (r *inputValueResolverImpl) DeprecationReason(ctx context.Context, obj *introspection.InputValue) (*string, error) {
	// InputValue doesn't have deprecation in gqlgen introspection
	return nil, nil
}

// IsOneOf is the resolver for the isOneOf field.
func (r *typeResolverImpl) IsOneOf(ctx context.Context, obj *introspection.Type) (*bool, error) {
	isOneOf := false
	return &isOneOf, nil
}

// inputValueResolverImpl implements __InputValueResolver interface
type inputValueResolverImpl struct{ *Resolver }

// typeResolverImpl implements __TypeResolver interface
type typeResolverImpl struct{ *Resolver }

// __InputValue returns __InputValueResolver implementation.
func (r *Resolver) __InputValue() __InputValueResolver { return &inputValueResolverImpl{r} }

// __Type returns __TypeResolver implementation.
func (r *Resolver) __Type() __TypeResolver { return &typeResolverImpl{r} }
