package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.60

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"runtime"
	"strconv"
	"strings"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/casapps/wthr/src/config"
	"github.com/casapps/wthr/src/server/handler"
	models "github.com/casapps/wthr/src/server/model"
	"github.com/casapps/wthr/src/server/service"
	utils "github.com/casapps/wthr/src/util"
)

// ExpiresAt is the resolver for the expiresAt field.
func (r *aPITokenResolver) ExpiresAt(ctx context.Context, obj *models.APIToken) (*time.Time, error) {
	if obj.ExpiresAt.Valid {
		return &obj.ExpiresAt.Time, nil
	}
	return nil, nil
}

// LastUsedIP is the resolver for the lastUsedIP field.
func (r *aPITokenResolver) LastUsedIP(ctx context.Context, obj *models.APIToken) (*string, error) {
	if obj.LastUsedIP.Valid {
		return &obj.LastUsedIP.String, nil
	}
	return nil, nil
}

// RegisterUser is the resolver for the registerUser field.
func (r *mutationResolver) RegisterUser(ctx context.Context, username string, email string, password string) (*AuthResult, error) {
	response, err := handler.RegisterAPIUser(r.UsersDB, &handler.APIRegisterRequest{
		Username: username,
		Email:    email,
		Password: password,
	})
	if err != nil {
		return nil, err
	}

	return mapGraphQLAuthRegisterResponse(response), nil
}

// LoginUser is the resolver for the loginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, identifier string, password string, twoFactorCode *string, recoveryKey *string) (*AuthResult, error) {
	req := &handler.APILoginRequest{
		Identifier: identifier,
		Password:   password,
	}
	if twoFactorCode != nil {
		req.TwoFactorCode = *twoFactorCode
	}
	if recoveryKey != nil {
		req.RecoveryKey = *recoveryKey
	}

	response, err := handler.LoginAPIUser(r.UsersDB, req, getIPFromContext(ctx))
	if err != nil {
		return nil, err
	}

	return mapGraphQLAuthLoginResponse(response), nil
}

// CompleteUserTwoFactor is the resolver for the completeUserTwoFactor field.
func (r *mutationResolver) CompleteUserTwoFactor(ctx context.Context, sessionToken string, twoFactorCode string) (*AuthResult, error) {
	response, err := handler.CompleteAPIUserTwoFactor(r.UsersDB, &handler.API2FARequest{
		SessionToken:  sessionToken,
		TwoFactorCode: twoFactorCode,
	}, getIPFromContext(ctx))
	if err != nil {
		return nil, err
	}

	return mapGraphQLAuthLoginResponse(response), nil
}

// UseUserRecoveryKey is the resolver for the useUserRecoveryKey field.
func (r *mutationResolver) UseUserRecoveryKey(ctx context.Context, sessionToken string, recoveryKey string) (*AuthResult, error) {
	response, err := handler.UseAPIUserRecoveryKey(r.UsersDB, &handler.APIRecoveryUseRequest{
		SessionToken: sessionToken,
		RecoveryKey:  recoveryKey,
	}, getIPFromContext(ctx))
	if err != nil {
		return nil, err
	}

	return mapGraphQLAuthLoginResponse(response), nil
}

// LogoutUser is the resolver for the logoutUser field.
func (r *mutationResolver) LogoutUser(ctx context.Context) (*GenericResponse, error) {
	session, err := loadGraphQLCurrentUserSession(ctx)
	if err != nil {
		return nil, err
	}

	if err := handler.LogoutCurrentUserSession(r.UsersDB, session); err != nil {
		return nil, err
	}

	return &GenericResponse{Success: true, Message: "Logged out successfully"}, nil
}

// RefreshUserSession is the resolver for the refreshUserSession field.
func (r *mutationResolver) RefreshUserSession(ctx context.Context) (*AuthResult, error) {
	session, err := loadGraphQLCurrentUserSession(ctx)
	if err != nil {
		return nil, err
	}

	user, err := loadGraphQLCurrentUserAuth(ctx, r.UsersDB)
	if err != nil {
		return nil, err
	}

	response, err := handler.RefreshCurrentUserSession(r.UsersDB, session, user)
	if err != nil {
		return nil, err
	}

	return mapGraphQLAuthLoginResponse(response), nil
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, email string) (*GenericResponse, error) {
	if err := handler.RequestAPIUserPasswordReset(r.UsersDB, &handler.APIPasswordForgotRequest{
		Email: email,
	}, &handler.APIPasswordResetContext{
		ClientIP: getIPFromContext(ctx),
		FullHost: graphQLRequestBaseURL(ctx),
	}); err != nil {
		return nil, err
	}

	return &GenericResponse{
		Success: true,
		Message: "If an account exists with that email, a password reset link will be sent",
	}, nil
}

// ResetUserPassword is the resolver for the resetUserPassword field.
func (r *mutationResolver) ResetUserPassword(ctx context.Context, token string, password string) (*GenericResponse, error) {
	if err := handler.ResetAPIUserPassword(r.UsersDB, &handler.APIPasswordResetRequest{
		Token:    token,
		Password: password,
	}); err != nil {
		return nil, err
	}

	return &GenericResponse{
		Success: true,
		Message: "Password reset successfully. Please log in with your new password.",
	}, nil
}

// VerifyUserEmail is the resolver for the verifyUserEmail field.
func (r *mutationResolver) VerifyUserEmail(ctx context.Context, token string) (*GenericResponse, error) {
	if err := handler.VerifyAPIUserEmail(r.UsersDB, &handler.APIVerifyEmailRequest{Token: token}); err != nil {
		return nil, err
	}

	return &GenericResponse{Success: true, Message: "Email verified successfully"}, nil
}

// CompleteUserInvite is the resolver for the completeUserInvite field.
func (r *mutationResolver) CompleteUserInvite(ctx context.Context, token string, username string, password string) (*UserInviteCompletion, error) {
	response, err := handler.CompleteAPIUserInvite(r.UsersDB, token, username, password)
	if err != nil {
		return nil, err
	}

	return mapGraphQLUserInviteCompletion(response), nil
}

// CompleteServerInvite is the resolver for the completeServerInvite field.
func (r *mutationResolver) CompleteServerInvite(ctx context.Context, token string, username string, password string) (*ServerInviteCompletion, error) {
	response, err := handler.CompleteAPIServerInvite(token, username, password)
	if err != nil {
		return nil, err
	}

	return mapGraphQLServerInviteCompletion(response), nil
}

// UpdateUserProfile is the resolver for the updateUserProfile field.
func (r *mutationResolver) UpdateUserProfile(ctx context.Context, displayName *string, phone *string) (*GenericResponse, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	req := &handler.UpdateCurrentUserProfileRequest{}
	if displayName != nil {
		req.DisplayName = *displayName
	}
	if phone != nil {
		req.Phone = *phone
	}

	if err := handler.UpdateCurrentUserProfile(r.UsersDB, int64(userID), req); err != nil {
		return nil, err
	}

	return &GenericResponse{Success: true, Message: "Profile updated successfully"}, nil
}

// UploadUserAvatar is the resolver for the uploadUserAvatar field.
func (r *mutationResolver) UploadUserAvatar(ctx context.Context, file graphql.Upload) (*PublicAvatar, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	avatar, err := handler.UploadCurrentUserAvatar(r.UsersDB, int64(userID), &handler.AvatarUploadRequest{
		Filename:    strings.TrimSpace(file.Filename),
		Size:        file.Size,
		ContentType: strings.TrimSpace(file.ContentType),
	})
	if err != nil {
		return nil, err
	}

	return &PublicAvatar{
		Type: avatar.Type,
		Urls: avatar.URLs,
	}, nil
}

// UpdateUserAvatar is the resolver for the updateUserAvatar field.
func (r *mutationResolver) UpdateUserAvatar(ctx context.Context, typeArg string, url *string) (*PublicAvatar, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	req := &handler.UpdateAvatarRequest{Type: strings.TrimSpace(typeArg)}
	if url != nil {
		req.URL = strings.TrimSpace(*url)
	}

	avatar, err := handler.UpdateCurrentUserAvatar(r.UsersDB, int64(userID), req)
	if err != nil {
		return nil, err
	}

	return &PublicAvatar{
		Type: avatar.Type,
		Urls: avatar.URLs,
	}, nil
}

// ResetUserAvatar is the resolver for the resetUserAvatar field.
func (r *mutationResolver) ResetUserAvatar(ctx context.Context) (*GenericResponse, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	if err := handler.ResetCurrentUserAvatar(r.UsersDB, int64(userID)); err != nil {
		return nil, fmt.Errorf("failed to reset avatar: %w", err)
	}

	return &GenericResponse{Success: true, Message: "Avatar reset to Gravatar"}, nil
}

// ChangeUserPassword is the resolver for the changeUserPassword field.
func (r *mutationResolver) ChangeUserPassword(ctx context.Context, currentPassword string, newPassword string) (*GenericResponse, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	if err := handler.ChangeCurrentUserPassword(r.UsersDB, int64(userID), &handler.ChangePasswordRequest{
		CurrentPassword: currentPassword,
		NewPassword:     newPassword,
	}); err != nil {
		return nil, err
	}

	return &GenericResponse{Success: true, Message: "Password changed successfully"}, nil
}

// EnableUserTwoFactor is the resolver for the enableUserTwoFactor field.
func (r *mutationResolver) EnableUserTwoFactor(ctx context.Context, secret string, code string) (*TOTPRecoveryKeys, error) {
	user, err := loadGraphQLCurrentUserAuth(ctx, r.UsersDB)
	if err != nil {
		return nil, err
	}

	response, err := handler.EnableCurrentUserTwoFactor(r.UsersDB, user, secret, code)
	if err != nil {
		return nil, err
	}

	return mapGraphQLRecoveryKeysResponse(response), nil
}

// DisableUserTwoFactor is the resolver for the disableUserTwoFactor field.
func (r *mutationResolver) DisableUserTwoFactor(ctx context.Context, password string) (*GenericResponse, error) {
	user, err := loadGraphQLCurrentUserAuth(ctx, r.UsersDB)
	if err != nil {
		return nil, err
	}

	if err := handler.DisableCurrentUserTwoFactor(r.UsersDB, user, password); err != nil {
		return nil, err
	}

	return &GenericResponse{Success: true, Message: "Two-factor authentication disabled successfully"}, nil
}

// VerifyUserTwoFactor is the resolver for the verifyUserTwoFactor field.
func (r *mutationResolver) VerifyUserTwoFactor(ctx context.Context, code string) (*GenericResponse, error) {
	user, err := loadGraphQLCurrentUserAuth(ctx, r.UsersDB)
	if err != nil {
		return nil, err
	}

	if err := handler.VerifyCurrentUserTwoFactorCode(r.UsersDB, user, code); err != nil {
		return nil, err
	}

	return &GenericResponse{Success: true, Message: "Code verified successfully"}, nil
}

// RegenerateUserRecoveryKeys is the resolver for the regenerateUserRecoveryKeys field.
func (r *mutationResolver) RegenerateUserRecoveryKeys(ctx context.Context, code string) (*TOTPRecoveryKeys, error) {
	user, err := loadGraphQLCurrentUserAuth(ctx, r.UsersDB)
	if err != nil {
		return nil, err
	}

	response, err := handler.RegenerateCurrentUserRecoveryKeys(r.UsersDB, user, code)
	if err != nil {
		return nil, err
	}

	return mapGraphQLRecoveryKeysResponse(response), nil
}

// BeginUserPasskeyRegistration is the resolver for the
// beginUserPasskeyRegistration field. NOTE: GraphQL dispatch wiring (in
// generated.go) for this field requires `gqlgen generate` to be re-run. The
// project ships an in-tree v0.17.60 generated.go that still has the upstream
// prelude.resolvers.go template bug, so the regen is currently blocked. The
// schema entry, the resolver method, and the supporting helpers in
// src/server/handler/passkey_helpers.go all exist and compile; they will
// activate as soon as the regen runs cleanly.
func (r *mutationResolver) BeginUserPasskeyRegistration(ctx context.Context, name string, password string) (*PasskeyRegistrationOptions, error) {
	user, err := loadGraphQLCurrentUserAuth(ctx, r.UsersDB)
	if err != nil {
		return nil, err
	}

	env, err := graphQLPasskeyEnvelope(ctx)
	if err != nil {
		return nil, err
	}

	result, err := handler.BeginPasskeyRegistrationToken(r.UsersDB, user, env, name, password)
	if err != nil {
		return nil, err
	}

	return &PasskeyRegistrationOptions{
		CeremonyToken: result.CeremonyToken,
		Options:       result.Options,
	}, nil
}

// FinishUserPasskeyRegistration is the resolver for the
// finishUserPasskeyRegistration field.
func (r *mutationResolver) FinishUserPasskeyRegistration(ctx context.Context, ceremonyToken string, credential any) (*PasskeyRegistrationResult, error) {
	user, err := loadGraphQLCurrentUserAuth(ctx, r.UsersDB)
	if err != nil {
		return nil, err
	}

	env, err := graphQLPasskeyEnvelope(ctx)
	if err != nil {
		return nil, err
	}

	body, err := json.Marshal(credential)
	if err != nil {
		return nil, fmt.Errorf("failed to encode passkey credential: %w", err)
	}

	result, err := handler.FinishPasskeyRegistrationToken(r.UsersDB, user, env, ceremonyToken, body)
	if err != nil {
		return nil, err
	}

	resp := &PasskeyRegistrationResult{
		Message: "Passkey registered successfully",
		Passkey: mapGraphQLPasskey(result.Passkey),
	}
	if len(result.RecoveryKeys) > 0 {
		resp.RecoveryKeys = append([]string(nil), result.RecoveryKeys...)
	}
	return resp, nil
}

// DeleteUserPasskey is the resolver for the deleteUserPasskey field.
func (r *mutationResolver) DeleteUserPasskey(ctx context.Context, id string) (*GenericResponse, error) {
	user, err := loadGraphQLCurrentUserAuth(ctx, r.UsersDB)
	if err != nil {
		return nil, err
	}

	passkeyID, err := strconv.ParseInt(strings.TrimSpace(id), 10, 64)
	if err != nil || passkeyID <= 0 {
		return nil, fmt.Errorf("Invalid passkey id")
	}

	if err := handler.DeleteUserPasskey(r.UsersDB, user.ID, passkeyID); err != nil {
		return nil, err
	}

	return &GenericResponse{Success: true, Message: "Passkey deleted successfully"}, nil
}

// BeginUserPasskeyChallenge is the resolver for the beginUserPasskeyChallenge
// field. Public mutation — no authentication required because passkey login
// is itself the authentication step.
func (r *mutationResolver) BeginUserPasskeyChallenge(ctx context.Context, sessionToken *string) (*PasskeyChallengeOptions, error) {
	env, err := graphQLPasskeyEnvelope(ctx)
	if err != nil {
		return nil, err
	}

	pendingToken := ""
	if sessionToken != nil {
		pendingToken = strings.TrimSpace(*sessionToken)
	}

	result, err := handler.BeginPasskeyChallengeToken(r.UsersDB, env, pendingToken)
	if err != nil {
		return nil, err
	}

	return &PasskeyChallengeOptions{
		CeremonyToken: result.CeremonyToken,
		Options:       result.Options,
	}, nil
}

// FinishUserPasskeyChallenge is the resolver for the finishUserPasskeyChallenge
// field. Public mutation — completes passkey login or the
// passkey-as-second-factor flow.
func (r *mutationResolver) FinishUserPasskeyChallenge(ctx context.Context, ceremonyToken string, credential any) (*AuthResult, error) {
	env, err := graphQLPasskeyEnvelope(ctx)
	if err != nil {
		return nil, err
	}

	body, err := json.Marshal(credential)
	if err != nil {
		return nil, fmt.Errorf("failed to encode passkey credential: %w", err)
	}

	response, err := handler.FinishPasskeyChallengeToken(r.UsersDB, env, ceremonyToken, body, getIPFromContext(ctx))
	if err != nil {
		return nil, err
	}

	return mapGraphQLAuthLoginResponse(response), nil
}

// UpdateUserSettings is the resolver for the updateUserSettings field.
func (r *mutationResolver) UpdateUserSettings(ctx context.Context, account *AccountSettingsInput, privacy *PrivacySettingsInput, notifications *NotificationSettingsInput, appearance *AppearanceSettingsInput) (*GenericResponse, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	req := &handler.UpdateSettingsRequest{}
	if account != nil {
		req.Account = &handler.AccountSettings{
			DisplayName: account.DisplayName,
			Bio:         account.Bio,
			Location:    account.Location,
			Website:     account.Website,
			Timezone:    account.Timezone,
			Language:    account.Language,
			DateFormat:  account.DateFormat,
			TimeFormat:  account.TimeFormat,
		}
	}
	if privacy != nil {
		req.Privacy = &handler.PrivacySettings{
			Visibility:    privacy.Visibility,
			ShowEmail:     privacy.ShowEmail,
			ShowActivity:  privacy.ShowActivity,
			ShowOrgs:      privacy.ShowOrgs,
			Searchable:    privacy.Searchable,
			OrgVisibility: privacy.OrgVisibility,
		}
	}
	if notifications != nil {
		req.Notifications = &handler.NotificationSettings{
			EmailSecurity: notifications.EmailSecurity,
			EmailMentions: notifications.EmailMentions,
			EmailUpdates:  notifications.EmailUpdates,
			EmailDigest:   notifications.EmailDigest,
			PushEnabled:   notifications.PushEnabled,
			PushMentions:  notifications.PushMentions,
		}
	}
	if appearance != nil {
		req.Appearance = &handler.AppearanceSettings{
			Theme:        appearance.Theme,
			FontSize:     appearance.FontSize,
			ReduceMotion: appearance.ReduceMotion,
		}
	}

	if err := handler.ApplyUserSettingsUpdate(r.UsersDB, int64(userID), req); err != nil {
		return nil, err
	}

	return &GenericResponse{Success: true, Message: "Settings updated successfully"}, nil
}

// CreateUserToken is the resolver for the createUserToken field.
func (r *mutationResolver) CreateUserToken(ctx context.Context, name string, scopes *string, expiresIn *int) (*UserToken, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	var count int
	if err := r.UsersDB.QueryRow("SELECT COUNT(*) FROM user_tokens WHERE user_id = ?", userID).Scan(&count); err != nil {
		return nil, fmt.Errorf("failed to count user tokens: %w", err)
	}
	if count >= 5 {
		return nil, fmt.Errorf("maximum 5 tokens per user")
	}

	token, err := models.GenerateTokenWithPrefix(models.PrefixUser)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	tokenHash := models.HashToken(token)
	tokenPrefix := models.GetTokenPrefix(token) + "..."
	createdAt := time.Now()

	var expiresAt sql.NullTime
	if expiresIn != nil && *expiresIn > 0 {
		expiresAt = sql.NullTime{
			Time:  createdAt.AddDate(0, 0, *expiresIn),
			Valid: true,
		}
	}

	var scopesValue string
	if scopes != nil {
		scopesValue = strings.TrimSpace(*scopes)
	}

	result, err := r.UsersDB.Exec(`
		INSERT INTO user_tokens (user_id, token_hash, token_prefix, name, scopes, created_at, expires_at)
		VALUES (?, ?, ?, ?, ?, ?, ?)
	`, userID, tokenHash, tokenPrefix, strings.TrimSpace(name), scopesValue, createdAt, expiresAt)
	if err != nil {
		return nil, fmt.Errorf("failed to create token: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return nil, fmt.Errorf("failed to load created token id: %w", err)
	}

	return buildGraphQLUserToken(
		id,
		strings.TrimSpace(name),
		tokenPrefix,
		scopesValue,
		createdAt,
		expiresAt,
		sql.NullTime{},
		&token,
	), nil
}

// RevokeUserToken is the resolver for the revokeUserToken field.
func (r *mutationResolver) RevokeUserToken(ctx context.Context, id string) (*GenericResponse, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	tokenID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid token id")
	}

	result, err := r.UsersDB.Exec("DELETE FROM user_tokens WHERE id = ? AND user_id = ?", tokenID, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to revoke token: %w", err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return nil, fmt.Errorf("failed to verify revoked token: %w", err)
	}
	if rowsAffected == 0 {
		return &GenericResponse{Success: false, Message: "Token not found"}, nil
	}

	return &GenericResponse{Success: true, Message: "Token revoked"}, nil
}

// CreateSavedLocation is the resolver for the createSavedLocation field.
func (r *mutationResolver) CreateSavedLocation(ctx context.Context, name string, lat float64, lon float64, country *string, region *string, alerts *bool) (*models.SavedLocation, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	alertsEnabled := true
	if alerts != nil {
		alertsEnabled = *alerts
	}

	timezone := ""
	result, err := r.UsersDB.Exec(`
		INSERT INTO user_saved_locations (user_id, name, latitude, longitude, timezone, alerts_enabled, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?)
	`, userID, name, lat, lon, timezone, alertsEnabled, time.Now(), time.Now())

	if err != nil {
		return nil, fmt.Errorf("failed to create location: %w", err)
	}

	id, err := result.LastInsertId()
	if err != nil {
		return nil, err
	}

	location := &models.SavedLocation{}
	err = r.UsersDB.QueryRow(`
		SELECT id, user_id, name, latitude, longitude, timezone, alerts_enabled, created_at, updated_at
		FROM user_saved_locations WHERE id = ?
	`, id).Scan(&location.ID, &location.UserID, &location.Name, &location.Latitude, &location.Longitude, &location.Timezone, &location.AlertsEnabled, &location.CreatedAt, &location.UpdatedAt)

	if err != nil {
		return nil, fmt.Errorf("failed to fetch location: %w", err)
	}

	return location, nil
}

// UpdateSavedLocation is the resolver for the updateSavedLocation field.
func (r *mutationResolver) UpdateSavedLocation(ctx context.Context, id string, name *string, alerts *bool) (*models.SavedLocation, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	if name != nil {
		_, err := r.UsersDB.Exec("UPDATE user_saved_locations SET name = ?, updated_at = ? WHERE id = ? AND user_id = ?", *name, time.Now(), id, userID)
		if err != nil {
			return nil, fmt.Errorf("failed to update name: %w", err)
		}
	}

	if alerts != nil {
		_, err := r.UsersDB.Exec("UPDATE user_saved_locations SET alerts_enabled = ?, updated_at = ? WHERE id = ? AND user_id = ?", *alerts, time.Now(), id, userID)
		if err != nil {
			return nil, fmt.Errorf("failed to update alerts: %w", err)
		}
	}

	location := &models.SavedLocation{}
	err := r.UsersDB.QueryRow(`
		SELECT id, user_id, name, latitude, longitude, timezone, alerts_enabled, created_at, updated_at
		FROM user_saved_locations WHERE id = ? AND user_id = ?
	`, id, userID).Scan(&location.ID, &location.UserID, &location.Name, &location.Latitude, &location.Longitude, &location.Timezone, &location.AlertsEnabled, &location.CreatedAt, &location.UpdatedAt)

	if err != nil {
		return nil, fmt.Errorf("failed to fetch location: %w", err)
	}

	return location, nil
}

// DeleteSavedLocation is the resolver for the deleteSavedLocation field.
func (r *mutationResolver) DeleteSavedLocation(ctx context.Context, id string) (*GenericResponse, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	result, err := r.UsersDB.Exec("DELETE FROM user_saved_locations WHERE id = ? AND user_id = ?", id, userID)
	if err != nil {
		return &GenericResponse{Success: false, Message: fmt.Sprintf("Failed to delete location: %v", err)}, nil
	}

	rows, _ := result.RowsAffected()
	if rows == 0 {
		return &GenericResponse{Success: false, Message: "Location not found"}, nil
	}

	return &GenericResponse{Success: true, Message: "Location deleted successfully"}, nil
}

// ToggleLocationAlerts is the resolver for the toggleLocationAlerts field.
func (r *mutationResolver) ToggleLocationAlerts(ctx context.Context, id string) (*models.SavedLocation, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	_, err := r.UsersDB.Exec(`
		UPDATE user_saved_locations 
		SET alerts_enabled = NOT alerts_enabled, updated_at = ? 
		WHERE id = ? AND user_id = ?
	`, time.Now(), id, userID)

	if err != nil {
		return nil, fmt.Errorf("failed to toggle alerts: %w", err)
	}

	location := &models.SavedLocation{}
	err = r.UsersDB.QueryRow(`
		SELECT id, user_id, name, latitude, longitude, timezone, alerts_enabled, created_at, updated_at
		FROM user_saved_locations WHERE id = ? AND user_id = ?
	`, id, userID).Scan(&location.ID, &location.UserID, &location.Name, &location.Latitude, &location.Longitude, &location.Timezone, &location.AlertsEnabled, &location.CreatedAt, &location.UpdatedAt)

	if err != nil {
		return nil, fmt.Errorf("failed to fetch location: %w", err)
	}

	return location, nil
}

// MarkNotificationRead is the resolver for the markNotificationRead field.
func (r *mutationResolver) MarkNotificationRead(ctx context.Context, id string) (*models.Notification, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	_, err := r.UsersDB.Exec(`
		UPDATE user_notifications 
		SET read = 1
		WHERE id = ? AND user_id = ?
	`, id, userID)

	if err != nil {
		return nil, fmt.Errorf("failed to mark notification as read: %w", err)
	}

	notification := &models.Notification{}
	var notificationUserID int
	err = r.UsersDB.QueryRow(`
		SELECT id, user_id, type, display, title, message, read, dismissed, created_at, expires_at
		FROM user_notifications WHERE id = ? AND user_id = ?
	`, id, userID).Scan(
		&notification.ID,
		&notificationUserID,
		&notification.Type,
		&notification.Display,
		&notification.Title,
		&notification.Message,
		&notification.Read,
		&notification.Dismissed,
		&notification.CreatedAt,
		&notification.ExpiresAt,
	)

	if err != nil {
		return nil, fmt.Errorf("failed to fetch notification: %w", err)
	}
	notification.UserID = &notificationUserID
	notification.IsRead = notification.Read

	return notification, nil
}

// MarkAllNotificationsRead is the resolver for the markAllNotificationsRead field.
func (r *mutationResolver) MarkAllNotificationsRead(ctx context.Context) (*GenericResponse, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	_, err := r.UsersDB.Exec(`
		UPDATE user_notifications 
		SET read = 1
		WHERE user_id = ? AND read = 0
	`, userID)

	if err != nil {
		return &GenericResponse{Success: false, Message: fmt.Sprintf("Failed to mark notifications as read: %v", err)}, nil
	}

	return &GenericResponse{Success: true, Message: "All notifications marked as read"}, nil
}

// DeleteNotification is the resolver for the deleteNotification field.
func (r *mutationResolver) DeleteNotification(ctx context.Context, id string) (*GenericResponse, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized")
	}

	result, err := r.UsersDB.Exec("DELETE FROM user_notifications WHERE id = ? AND user_id = ?", id, userID)
	if err != nil {
		return &GenericResponse{Success: false, Message: fmt.Sprintf("Failed to delete notification: %v", err)}, nil
	}

	rows, _ := result.RowsAffected()
	if rows == 0 {
		return &GenericResponse{Success: false, Message: "Notification not found"}, nil
	}

	return &GenericResponse{Success: true, Message: "Notification deleted successfully"}, nil
}

// AdminUpdateUser is the resolver for the adminUpdateUser field.
func (r *mutationResolver) AdminUpdateUser(ctx context.Context, id string, username *string, email *string, role *string) (*models.User, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	userID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}

	userModel := &models.UserModel{DB: r.UsersDB}
	user, err := userModel.GetByID(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to load user: %w", err)
	}

	updatedUsername := user.Username
	if username != nil {
		updatedUsername = utils.NormalizeUsername(*username)
		if err := utils.ValidateUsername(updatedUsername); err != nil {
			return nil, err
		}
	}

	updatedEmail := user.Email
	if email != nil {
		updatedEmail = utils.NormalizeEmail(*email)
		if err := utils.ValidateEmail(updatedEmail); err != nil {
			return nil, err
		}
	}

	updatedRole := user.Role
	if role != nil && strings.TrimSpace(*role) != "" {
		updatedRole = strings.TrimSpace(*role)
	}

	if err := userModel.Update(userID, updatedUsername, updatedEmail, updatedRole); err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	user, err = userModel.GetByID(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch user: %w", err)
	}

	user.Email = utils.MaskEmail(user.Email)
	return user, nil
}

// AdminDeleteUser is the resolver for the adminDeleteUser field.
func (r *mutationResolver) AdminDeleteUser(ctx context.Context, id string) (*GenericResponse, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	userID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid user id")
	}

	userModel := &models.UserModel{DB: r.UsersDB}
	if _, err := userModel.GetByID(userID); err != nil {
		return &GenericResponse{Success: false, Message: "User not found"}, nil
	}
	if err := userModel.Delete(userID); err != nil {
		return &GenericResponse{Success: false, Message: fmt.Sprintf("Failed to delete user: %v", err)}, nil
	}

	return &GenericResponse{Success: true, Message: "User deleted successfully"}, nil
}

// AdminCreateUserInvite is the resolver for the adminCreateUserInvite field.
func (r *mutationResolver) AdminCreateUserInvite(ctx context.Context, username string, email string, role *string, expiresInDays *int) (*UserInvite, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	normalizedUsername := utils.NormalizeUsername(username)
	if err := utils.ValidateUsername(normalizedUsername); err != nil {
		return nil, err
	}

	normalizedEmail := utils.NormalizeEmail(email)
	if err := utils.ValidateEmail(normalizedEmail); err != nil {
		return nil, err
	}

	userModel := &models.UserModel{DB: r.UsersDB}
	if _, err := userModel.GetByUsername(normalizedUsername); err == nil {
		return nil, fmt.Errorf("username is already in use")
	}
	if _, err := userModel.GetByEmail(normalizedEmail); err == nil {
		return nil, fmt.Errorf("email is already in use")
	}

	inviteRole := "user"
	if role != nil && strings.TrimSpace(*role) != "" {
		inviteRole = strings.TrimSpace(*role)
	}

	inviteDays := config.GetUserInviteExpirationDays()
	if expiresInDays != nil && *expiresInDays > 0 {
		inviteDays = *expiresInDays
	}

	inviteModel := &models.UserInviteModel{DB: r.UsersDB}
	invite, err := inviteModel.CreateInvite(normalizedUsername, normalizedEmail, inviteRole, inviteDays)
	if err != nil {
		return nil, err
	}

	return buildGraphQLUserInvite(invite, ctx), nil
}

// AdminDeleteUserInvite is the resolver for the adminDeleteUserInvite field.
func (r *mutationResolver) AdminDeleteUserInvite(ctx context.Context, id string) (*GenericResponse, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	inviteID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid invite id")
	}

	inviteModel := &models.UserInviteModel{DB: r.UsersDB}
	if err := inviteModel.DeleteInvite(inviteID); err != nil {
		return nil, err
	}

	return &GenericResponse{Success: true, Message: "Invite revoked"}, nil
}

// AdminInviteServerAdmin is the resolver for the adminInviteServerAdmin field.
func (r *mutationResolver) AdminInviteServerAdmin(ctx context.Context, email string, expiresIn *string) (*ServerAdminInvite, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	currentAdmin, err := loadGraphQLCurrentAdmin(ctx, r.ServerDB)
	if err != nil {
		return nil, err
	}

	expiration := ""
	if expiresIn != nil {
		expiration = strings.TrimSpace(*expiresIn)
	}

	inviteService := service.NewAdminInviteService(r.ServerDB, "", nil)
	invite, normalizedExpiration, err := inviteService.CreateInvite(email, int(currentAdmin.ID), expiration)
	if err != nil {
		return nil, err
	}

	return buildGraphQLServerAdminInvite(ctx, invite, normalizedExpiration), nil
}

// AdminDeleteServerAdmin is the resolver for the adminDeleteServerAdmin field.
func (r *mutationResolver) AdminDeleteServerAdmin(ctx context.Context, id string) (*GenericResponse, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	currentAdmin, err := loadGraphQLCurrentAdmin(ctx, r.ServerDB)
	if err != nil {
		return nil, err
	}

	adminID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid admin id")
	}

	if adminID == currentAdmin.ID {
		return &GenericResponse{Success: false, Message: "You cannot delete your own admin account"}, nil
	}
	if adminID == 1 {
		return &GenericResponse{Success: false, Message: "Primary admin account cannot be deleted"}, nil
	}

	adminModel := &models.AdminModel{DB: r.ServerDB}
	admin, err := adminModel.GetByID(adminID)
	if err != nil {
		return &GenericResponse{Success: false, Message: "Admin not found"}, nil
	}
	if admin.IsSuperAdmin && admin.IsActive {
		otherSuperAdmins, err := countGraphQLOtherActiveSuperAdmins(r.ServerDB, adminID)
		if err != nil {
			return nil, err
		}
		if otherSuperAdmins == 0 {
			return &GenericResponse{Success: false, Message: "Cannot delete the last active super admin"}, nil
		}
	}

	if err := adminModel.Delete(adminID); err != nil {
		return nil, fmt.Errorf("failed to delete admin: %w", err)
	}

	return &GenericResponse{Success: true, Message: "Admin deleted"}, nil
}

// AdminDisableServerAdmin is the resolver for the adminDisableServerAdmin field.
func (r *mutationResolver) AdminDisableServerAdmin(ctx context.Context, id string) (*GenericResponse, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	currentAdmin, err := loadGraphQLCurrentAdmin(ctx, r.ServerDB)
	if err != nil {
		return nil, err
	}

	adminID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid admin id")
	}

	if adminID == currentAdmin.ID {
		return &GenericResponse{Success: false, Message: "You cannot disable your own admin account"}, nil
	}
	if adminID == 1 {
		return &GenericResponse{Success: false, Message: "Primary admin account cannot be disabled"}, nil
	}

	adminModel := &models.AdminModel{DB: r.ServerDB}
	admin, err := adminModel.GetByID(adminID)
	if err != nil {
		return &GenericResponse{Success: false, Message: "Admin not found"}, nil
	}
	if admin.IsSuperAdmin && admin.IsActive {
		otherSuperAdmins, err := countGraphQLOtherActiveSuperAdmins(r.ServerDB, adminID)
		if err != nil {
			return nil, err
		}
		if otherSuperAdmins == 0 {
			return &GenericResponse{Success: false, Message: "Cannot disable the last active super admin"}, nil
		}
	}

	if err := adminModel.Update(admin.ID, admin.Username, admin.Email, admin.IsSuperAdmin, false); err != nil {
		return nil, fmt.Errorf("failed to disable admin: %w", err)
	}

	return &GenericResponse{Success: true, Message: "Admin disabled"}, nil
}

// AdminEnableServerAdmin is the resolver for the adminEnableServerAdmin field.
func (r *mutationResolver) AdminEnableServerAdmin(ctx context.Context, id string) (*GenericResponse, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	adminID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid admin id")
	}

	adminModel := &models.AdminModel{DB: r.ServerDB}
	admin, err := adminModel.GetByID(adminID)
	if err != nil {
		return &GenericResponse{Success: false, Message: "Admin not found"}, nil
	}

	if err := adminModel.Update(admin.ID, admin.Username, admin.Email, admin.IsSuperAdmin, true); err != nil {
		return nil, fmt.Errorf("failed to enable admin: %w", err)
	}

	return &GenericResponse{Success: true, Message: "Admin enabled"}, nil
}

// AdminUpdateSetting is the resolver for the adminUpdateSetting field.
func (r *mutationResolver) AdminUpdateSetting(ctx context.Context, key string, value string) (*models.Setting, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	result, err := r.ServerDB.Exec(`
		UPDATE server_config
		SET value = ?, updated_at = CURRENT_TIMESTAMP
		WHERE key = ?
	`, value, key)
	if err != nil {
		return nil, fmt.Errorf("failed to update setting: %w", err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return nil, fmt.Errorf("failed to verify updated setting: %w", err)
	}
	if rowsAffected == 0 {
		return nil, fmt.Errorf("setting not found: %s", key)
	}

	return loadGraphQLSetting(r.ServerDB, key)
}

// AdminUpdateSettings is the resolver for the adminUpdateSettings field.
func (r *mutationResolver) AdminUpdateSettings(ctx context.Context, settings []*SettingInput) (*BulkResponse, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	successCount := 0
	failedCount := 0

	for _, setting := range settings {
		result, err := r.ServerDB.Exec(`
			UPDATE server_config
			SET value = ?, updated_at = CURRENT_TIMESTAMP
			WHERE key = ?
		`, setting.Value, setting.Key)
		if err != nil {
			failedCount++
			continue
		}

		rowsAffected, err := result.RowsAffected()
		if err != nil || rowsAffected == 0 {
			failedCount++
			continue
		}

		successCount++
	}

	return &BulkResponse{
		Ok:      failedCount == 0,
		Updated: &successCount,
		Failed:  &failedCount,
	}, nil
}

// AdminResetSettings is the resolver for the adminResetSettings field.
func (r *mutationResolver) AdminResetSettings(ctx context.Context) (*GenericResponse, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	settingsModel := &models.SettingsModel{DB: r.ServerDB}
	backupPath := settingsModel.GetString("backup.location", "/data/backups")

	tx, err := r.ServerDB.Begin()
	if err != nil {
		return nil, fmt.Errorf("failed to start settings reset: %w", err)
	}
	defer tx.Rollback()

	if _, err := tx.Exec("DELETE FROM server_config"); err != nil {
		return nil, fmt.Errorf("failed to clear settings: %w", err)
	}
	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("failed to commit settings reset: %w", err)
	}

	if err := settingsModel.InitializeDefaults(backupPath); err != nil {
		return nil, fmt.Errorf("failed to restore default settings: %w", err)
	}

	return &GenericResponse{Success: true, Message: "All settings reset to defaults"}, nil
}

// AdminGenerateToken is the resolver for the adminGenerateToken field.
func (r *mutationResolver) AdminGenerateToken(ctx context.Context) (*models.APIToken, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	adminID, ok := ctx.Value("admin_id").(int)
	if !ok || adminID <= 0 {
		return nil, fmt.Errorf("unauthorized: admin session required")
	}

	adminModel := &models.AdminModel{DB: r.ServerDB}
	token, err := adminModel.RegenerateAPIToken(int64(adminID))
	if err != nil {
		return nil, fmt.Errorf("failed to regenerate admin API token: %w", err)
	}

	admin, err := adminModel.GetByID(int64(adminID))
	if err != nil {
		return nil, fmt.Errorf("failed to load regenerated admin token metadata: %w", err)
	}

	return &models.APIToken{
		ID:          int(admin.ID),
		Token:       token,
		TokenPrefix: admin.APITokenPrefix,
		CreatedAt:   admin.UpdatedAt,
	}, nil
}

// AdminRevokeToken is the resolver for the adminRevokeToken field.
func (r *mutationResolver) AdminRevokeToken(ctx context.Context, id string) (*GenericResponse, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	adminID, ok := ctx.Value("admin_id").(int)
	if !ok || adminID <= 0 {
		return nil, fmt.Errorf("unauthorized: admin session required")
	}

	if id != strconv.Itoa(adminID) {
		return &GenericResponse{Success: false, Message: "Token not found"}, nil
	}

	adminModel := &models.AdminModel{DB: r.ServerDB}
	if err := adminModel.RevokeAPIToken(int64(adminID)); err != nil {
		return nil, fmt.Errorf("failed to revoke admin API token: %w", err)
	}

	return &GenericResponse{Success: true, Message: "Token revoked successfully"}, nil
}

// AdminClearAuditLogs is the resolver for the adminClearAuditLogs field.
func (r *mutationResolver) AdminClearAuditLogs(ctx context.Context) (*GenericResponse, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	_, err := r.ServerDB.Exec("DELETE FROM server_audit_log")
	if err != nil {
		return nil, fmt.Errorf("failed to clear audit logs: %w", err)
	}

	return &GenericResponse{Success: true, Message: "Audit logs cleared successfully"}, nil
}

// AdminUpdateTask is the resolver for the adminUpdateTask field.
func (r *mutationResolver) AdminUpdateTask(ctx context.Context, name string, enabled bool) (*ScheduledTask, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	task, err := r.updateGraphQLScheduledTaskEnabled(name, enabled)
	if err != nil {
		return nil, fmt.Errorf("failed to update task: %w", err)
	}

	return task, nil
}

// AdminEnableTask is the resolver for the adminEnableTask field.
func (r *mutationResolver) AdminEnableTask(ctx context.Context, name string) (*ScheduledTask, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	task, err := r.updateGraphQLScheduledTaskEnabled(name, true)
	if err != nil {
		return nil, fmt.Errorf("failed to enable task: %w", err)
	}

	return task, nil
}

// AdminDisableTask is the resolver for the adminDisableTask field.
func (r *mutationResolver) AdminDisableTask(ctx context.Context, name string) (*ScheduledTask, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	task, err := r.updateGraphQLScheduledTaskEnabled(name, false)
	if err != nil {
		return nil, fmt.Errorf("failed to disable task: %w", err)
	}

	return task, nil
}

// AdminTriggerTask is the resolver for the adminTriggerTask field.
func (r *mutationResolver) AdminTriggerTask(ctx context.Context, name string) (*GenericResponse, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	err := r.SchedulerHandler.Scheduler.TriggerTask(name)
	if err != nil {
		return nil, fmt.Errorf("failed to trigger task: %w", err)
	}

	return &GenericResponse{Success: true, Message: fmt.Sprintf("Task '%s' triggered successfully", name)}, nil
}

// AdminUpdateChannel is the resolver for the adminUpdateChannel field.
func (r *mutationResolver) AdminUpdateChannel(ctx context.Context, typeArg string, enabled *bool, config any) (*NotificationChannel, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	if enabled != nil {
		channelManager := service.NewChannelManager(r.ServerDB)
		var err error
		if *enabled {
			err = channelManager.EnableChannel(typeArg)
		} else {
			err = channelManager.DisableChannel(typeArg)
		}
		if err != nil {
			return nil, fmt.Errorf("failed to update channel state: %w", err)
		}
	}

	if config != nil {
		configJSON, err := json.Marshal(config)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal channel config: %w", err)
		}

		_, err = r.ServerDB.Exec(`
			UPDATE notification_channels
			SET config = ?, updated_at = datetime('now')
			WHERE channel_type = ?
		`, string(configJSON), typeArg)
		if err != nil {
			return nil, fmt.Errorf("failed to update channel config: %w", err)
		}
	}

	return loadGraphQLNotificationChannel(r.ServerDB, typeArg)
}

// AdminEnableChannel is the resolver for the adminEnableChannel field.
func (r *mutationResolver) AdminEnableChannel(ctx context.Context, typeArg string) (*NotificationChannel, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	channelManager := service.NewChannelManager(r.ServerDB)
	if err := channelManager.EnableChannel(typeArg); err != nil {
		return nil, fmt.Errorf("failed to enable channel: %w", err)
	}

	return loadGraphQLNotificationChannel(r.ServerDB, typeArg)
}

// AdminDisableChannel is the resolver for the adminDisableChannel field.
func (r *mutationResolver) AdminDisableChannel(ctx context.Context, typeArg string) (*NotificationChannel, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	channelManager := service.NewChannelManager(r.ServerDB)
	if err := channelManager.DisableChannel(typeArg); err != nil {
		return nil, fmt.Errorf("failed to disable channel: %w", err)
	}

	return loadGraphQLNotificationChannel(r.ServerDB, typeArg)
}

// AdminTestChannel is the resolver for the adminTestChannel field.
func (r *mutationResolver) AdminTestChannel(ctx context.Context, typeArg string, recipient *string) (*GenericResponse, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	recipientValue, err := r.resolveAdminChannelTestRecipient(ctx, typeArg, recipient)
	if err != nil {
		return nil, err
	}

	channelManager := service.NewChannelManager(r.ServerDB)
	if typeArg == "email" {
		smtpService := service.NewSMTPService(r.ServerDB)
		if err := smtpService.LoadConfig(); err != nil {
			return nil, fmt.Errorf("failed to load SMTP configuration: %w", err)
		}
		channelManager.RegisterChannel(service.NewEmailChannel(smtpService))
	}

	if err := channelManager.TestChannel(typeArg, recipientValue); err != nil {
		return nil, fmt.Errorf("failed to send test %s notification: %w", typeArg, err)
	}

	message := fmt.Sprintf("Test %s notification sent successfully to %s", typeArg, recipientValue)
	if typeArg == "email" {
		message = fmt.Sprintf("Test email sent successfully to %s", recipientValue)
	}

	return &GenericResponse{
		Success: true,
		Message: message,
	}, nil
}

// AdminInitializeChannels is the resolver for the adminInitializeChannels field.
func (r *mutationResolver) AdminInitializeChannels(ctx context.Context) (*GenericResponse, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	channelManager := service.NewChannelManager(r.ServerDB)
	if err := channelManager.InitializeChannels(); err != nil {
		return nil, fmt.Errorf("failed to initialize notification channels: %w", err)
	}

	return &GenericResponse{
		Success: true,
		Message: fmt.Sprintf("Channels initialized successfully (%d registered definitions)", len(service.ChannelRegistry)),
	}, nil
}

// AdminAutoDetectSMTP is the resolver for the adminAutoDetectSMTP field.
func (r *mutationResolver) AdminAutoDetectSMTP(ctx context.Context) (*SMTPProvider, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	smtpService := service.NewSMTPService(r.ServerDB)
	found, err := smtpService.AutoDetect()
	if err != nil {
		return nil, fmt.Errorf("failed to auto-detect SMTP server: %w", err)
	}
	if !found {
		return nil, fmt.Errorf("no SMTP server detected")
	}

	if err := smtpService.LoadConfig(); err != nil {
		return nil, fmt.Errorf("failed to load detected SMTP config: %w", err)
	}

	smtpConfig := smtpService.GetConfig()
	if smtpConfig == nil || smtpConfig.Host == "" {
		return nil, fmt.Errorf("detected SMTP configuration is unavailable")
	}

	providerName := "Detected SMTP"
	for _, preset := range service.SMTPProviderPresets {
		if preset.Host == smtpConfig.Host && preset.Port == smtpConfig.Port {
			providerName = preset.Name
			break
		}
	}

	port, err := strconv.Atoi(smtpConfig.Port)
	if err != nil {
		return nil, fmt.Errorf("invalid detected SMTP port %q: %w", smtpConfig.Port, err)
	}

	return &SMTPProvider{
		Name:   providerName,
		Host:   smtpConfig.Host,
		Port:   port,
		Secure: smtpConfig.UseTLS,
	}, nil
}

// BeginAdminPasskeyRegistration is the resolver for the beginAdminPasskeyRegistration field.
// Requires admin auth. Verifies the admin's password then returns WebAuthn
// registration options and a ceremony token.
func (r *mutationResolver) BeginAdminPasskeyRegistration(ctx context.Context, name string, password string) (*PasskeyRegistrationOptions, error) {
	admin, err := loadGraphQLCurrentAdmin(ctx, r.ServerDB)
	if err != nil {
		return nil, err
	}

	env, err := graphQLPasskeyEnvelope(ctx)
	if err != nil {
		return nil, err
	}

	result, err := handler.BeginAdminPasskeyRegistrationToken(r.ServerDB, admin, env, name, password)
	if err != nil {
		return nil, err
	}

	return &PasskeyRegistrationOptions{
		CeremonyToken: result.CeremonyToken,
		Options:       result.Options,
	}, nil
}

// FinishAdminPasskeyRegistration is the resolver for the finishAdminPasskeyRegistration field.
// Requires admin auth. Completes the WebAuthn ceremony and persists the passkey.
func (r *mutationResolver) FinishAdminPasskeyRegistration(ctx context.Context, ceremonyToken string, credential any) (*AdminPasskeyRegistrationResult, error) {
	admin, err := loadGraphQLCurrentAdmin(ctx, r.ServerDB)
	if err != nil {
		return nil, err
	}

	env, err := graphQLPasskeyEnvelope(ctx)
	if err != nil {
		return nil, err
	}

	body, err := json.Marshal(credential)
	if err != nil {
		return nil, fmt.Errorf("failed to encode passkey credential: %w", err)
	}

	result, err := handler.FinishAdminPasskeyRegistrationToken(r.ServerDB, admin, env, ceremonyToken, body)
	if err != nil {
		return nil, err
	}

	return &AdminPasskeyRegistrationResult{
		Message: "Passkey registered successfully",
		Passkey: mapGraphQLAdminPasskey(result.Passkey),
	}, nil
}

// DeleteAdminPasskey is the resolver for the deleteAdminPasskey field.
// Requires admin auth. Deletes one of the authenticated admin's passkeys.
func (r *mutationResolver) DeleteAdminPasskey(ctx context.Context, id string) (*GenericResponse, error) {
	admin, err := loadGraphQLCurrentAdmin(ctx, r.ServerDB)
	if err != nil {
		return nil, err
	}

	passkeyID, err := strconv.ParseInt(strings.TrimSpace(id), 10, 64)
	if err != nil || passkeyID <= 0 {
		return nil, fmt.Errorf("Invalid passkey id")
	}

	if err := handler.DeleteAdminPasskey(r.ServerDB, admin.ID, passkeyID); err != nil {
		return nil, err
	}

	return &GenericResponse{Success: true, Message: "Passkey deleted successfully"}, nil
}

// BeginAdminPasskeyChallenge is the resolver for the beginAdminPasskeyChallenge field.
// Public mutation — the pending session token (issued after password verify)
// authenticates the request. Returns WebAuthn assertion options.
func (r *mutationResolver) BeginAdminPasskeyChallenge(ctx context.Context, sessionToken string) (*PasskeyChallengeOptions, error) {
	env, err := graphQLPasskeyEnvelope(ctx)
	if err != nil {
		return nil, err
	}

	result, err := handler.BeginAdminPasskeyLoginToken(r.ServerDB, env, strings.TrimSpace(sessionToken))
	if err != nil {
		return nil, err
	}

	return &PasskeyChallengeOptions{
		CeremonyToken: result.CeremonyToken,
		Options:       result.Options,
	}, nil
}

// FinishAdminPasskeyChallenge is the resolver for the finishAdminPasskeyChallenge field.
// Public mutation — completes the admin passkey login ceremony. Returns a
// session token (the caller must set the admin_session cookie via the REST
// verify endpoint; GraphQL callers receive the session ID for use in
// subsequent authenticated requests).
func (r *mutationResolver) FinishAdminPasskeyChallenge(ctx context.Context, ceremonyToken string, credential any) (*AdminLoginResult, error) {
	env, err := graphQLPasskeyEnvelope(ctx)
	if err != nil {
		return nil, err
	}

	body, err := json.Marshal(credential)
	if err != nil {
		return nil, fmt.Errorf("failed to encode passkey credential: %w", err)
	}

	clientIP := getIPFromContext(ctx)
	userAgent, _ := ctx.Value("request_user_agent").(string)

	const adminSessionDuration = 30 * 24 * time.Hour
	result, err := handler.FinishAdminPasskeyLoginToken(r.ServerDB, env, ceremonyToken, body, clientIP, userAgent, adminSessionDuration)
	if err != nil {
		return nil, err
	}

	expiresAt := result.ExpiresAt
	return &AdminLoginResult{
		SessionToken: result.SessionID,
		ExpiresAt:    &expiresAt,
	}, nil
}

// SubmitContactForm is the resolver for the submitContactForm field.
func (r *mutationResolver) SubmitContactForm(ctx context.Context, name string, email string, subject string, message string) (*ContactSubmission, error) {
	if err := ensureGraphQLContactSubmissionsTable(r.ServerDB); err != nil {
		return nil, fmt.Errorf("failed to prepare contact submission storage: %w", err)
	}

	requestIP, _ := ctx.Value("request_ip").(string)
	userAgent, _ := ctx.Value("request_user_agent").(string)

	_, err := r.ServerDB.Exec(`
		INSERT INTO contact_submissions (name, email, subject, message, ip_address, user_agent)
		VALUES (?, ?, ?, ?, ?, ?)
	`, name, email, subject, message, strings.TrimSpace(requestIP), strings.TrimSpace(userAgent))
	if err != nil {
		return nil, fmt.Errorf("failed to submit contact form: %w", err)
	}

	return &ContactSubmission{
		Ok:      true,
		Message: "Your message has been saved. We'll respond as soon as possible.",
	}, nil
}

// Type is the resolver for the type field. The model stores the value as a
// NotificationType custom string type; the GraphQL schema exposes a plain
// String, so this resolver does the str() coercion.
func (r *notificationResolver) Type(ctx context.Context, obj *models.Notification) (string, error) {
	if obj == nil {
		return "", nil
	}
	return string(obj.Type), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*HealthStatus, error) {
	initStatus := handler.GetInitStatus()
	now := time.Now()
	uptime := now.Sub(initStatus.Started).Round(time.Second).String()

	status := "healthy"
	message := "Service is running"

	var (
		dbHealth  *DatabaseHealth
		dbErrText *string
	)
	if r.ServerDB != nil {
		start := time.Now()
		err := r.ServerDB.PingContext(ctx)
		latency := int(time.Since(start).Milliseconds())
		dbHealth = &DatabaseHealth{
			Status:  "ok",
			Latency: &latency,
		}
		if err != nil {
			status = "unhealthy"
			message = "Database connectivity check failed"
			errText := err.Error()
			dbErrText = &errText
			dbHealth.Status = "error"
			dbHealth.Error = dbErrText
		}
	}

	if status == "healthy" && !handler.IsInitialized() {
		status = "initializing"
		message = "Services are still initializing"
	}

	var mem runtime.MemStats
	runtime.ReadMemStats(&mem)
	memoryHealth := &MemoryHealth{
		Used:       float64(mem.Alloc),
		Total:      float64(mem.Sys),
		Percentage: 0,
	}
	if mem.Sys > 0 {
		memoryHealth.Percentage = (float64(mem.Alloc) / float64(mem.Sys)) * 100
	}

	return &HealthStatus{
		Status:   status,
		Message:  &message,
		Database: dbHealth,
		Memory:   memoryHealth,
		LocationDatabases: &LocationDatabasesHealth{
			Countries: &LocationDBStatus{Loaded: initStatus.Countries},
			Cities:    &LocationDBStatus{Loaded: initStatus.Cities},
		},
		Uptime:    uptime,
		Timestamp: now,
	}, nil
}

// Weather is the resolver for the weather field.
func (r *queryResolver) Weather(ctx context.Context, location *string, lat *float64, lon *float64) (*Weather, error) {
	if r.WeatherService == nil {
		return nil, fmt.Errorf("weather service not initialized")
	}

	// Validate inputs
	if (location == nil || *location == "") && (lat == nil || lon == nil) {
		return nil, fmt.Errorf("either location name or coordinates (lat/lon) must be provided")
	}

	// Get coordinates from location or use provided lat/lon
	var latitude, longitude float64
	var locationName, country, timezone string

	if lat != nil && lon != nil {
		// Use provided coordinates
		latitude = *lat
		longitude = *lon
		// Reverse geocode to get location name
		coords, err := r.WeatherService.ReverseGeocode(latitude, longitude)
		if err == nil && coords != nil {
			locationName = coords.Name
			country = coords.Country
			timezone = coords.Timezone
		} else {
			locationName = fmt.Sprintf("%.4f, %.4f", latitude, longitude)
			country = "Unknown"
		}
	} else if location != nil && *location != "" {
		// Geocode location name to coordinates
		coords, err := r.WeatherService.GetCoordinates(*location, "")
		if err != nil {
			return nil, fmt.Errorf("could not find location: %s", *location)
		}
		latitude = coords.Latitude
		longitude = coords.Longitude
		locationName = coords.Name
		country = coords.Country
		timezone = coords.Timezone
	}

	// Get current weather
	current, err := r.WeatherService.GetCurrentWeather(latitude, longitude, "imperial")
	if err != nil {
		return nil, fmt.Errorf("failed to get weather: %w", err)
	}

	// Build response
	feelsLike := current.FeelsLike
	pressure := current.Pressure
	precipitation := current.Precipitation
	cloudCover := current.CloudCover

	return &Weather{
		Location: &Location{
			Name:     locationName,
			Country:  country,
			Lat:      latitude,
			Lon:      longitude,
			Timezone: &timezone,
		},
		Current: &CurrentWeather{
			Temperature:   current.Temperature,
			FeelsLike:     &feelsLike,
			Humidity:      current.Humidity,
			Pressure:      &pressure,
			WindSpeed:     current.WindSpeed,
			Precipitation: &precipitation,
			CloudCover:    &cloudCover,
			Condition: &WeatherCondition{
				Text: r.WeatherService.GetWeatherDescription(current.WeatherCode),
				Icon: stringPtr(r.WeatherService.GetWeatherIcon(current.WeatherCode, current.IsDay == 1)),
			},
			LastUpdated: time.Now(),
		},
		Timestamp: time.Now(),
	}, nil
}

// Forecast is the resolver for the forecast field.
func (r *queryResolver) Forecast(ctx context.Context, location *string, lat *float64, lon *float64, days *int) (*Weather, error) {
	if r.WeatherService == nil {
		return nil, fmt.Errorf("weather service not initialized")
	}

	// Validate inputs
	if (location == nil || *location == "") && (lat == nil || lon == nil) {
		return nil, fmt.Errorf("either location name or coordinates (lat/lon) must be provided")
	}

	// Default to 7 days if not specified
	numDays := 7
	if days != nil && *days > 0 && *days <= 16 {
		numDays = *days
	}

	// Get coordinates from location or use provided lat/lon
	var latitude, longitude float64
	var locationName, country, timezone string

	if lat != nil && lon != nil {
		// Use provided coordinates
		latitude = *lat
		longitude = *lon
		// Reverse geocode to get location name
		coords, err := r.WeatherService.ReverseGeocode(latitude, longitude)
		if err == nil && coords != nil {
			locationName = coords.Name
			country = coords.Country
			timezone = coords.Timezone
		} else {
			locationName = fmt.Sprintf("%.4f, %.4f", latitude, longitude)
			country = "Unknown"
		}
	} else if location != nil && *location != "" {
		// Geocode location name to coordinates
		coords, err := r.WeatherService.GetCoordinates(*location, "")
		if err != nil {
			return nil, fmt.Errorf("could not find location: %s", *location)
		}
		latitude = coords.Latitude
		longitude = coords.Longitude
		locationName = coords.Name
		country = coords.Country
		timezone = coords.Timezone
	}

	// Get forecast
	forecast, err := r.WeatherService.GetForecast(latitude, longitude, numDays, "imperial")
	if err != nil {
		return nil, fmt.Errorf("failed to get forecast: %w", err)
	}

	// Convert forecast days to GraphQL type
	var forecastDays []*ForecastDay
	for _, day := range forecast.Days {
		precipitation := day.Precipitation
		chanceOfRain := day.PrecipitationProbability
		forecastDays = append(forecastDays, &ForecastDay{
			Date: day.Date,
			Day: &DayForecast{
				MaxTemp:            day.TempMax,
				MinTemp:            day.TempMin,
				TotalPrecipitation: &precipitation,
				ChanceOfRain:       &chanceOfRain,
				Condition: &WeatherCondition{
					Text: r.WeatherService.GetWeatherDescription(day.WeatherCode),
					Icon: stringPtr(r.WeatherService.GetWeatherIcon(day.WeatherCode, true)),
				},
			},
		})
	}

	return &Weather{
		Location: &Location{
			Name:     locationName,
			Country:  country,
			Lat:      latitude,
			Lon:      longitude,
			Timezone: &timezone,
		},
		Forecast:  forecastDays,
		Timestamp: time.Now(),
	}, nil
}

// SearchLocations is the resolver for the searchLocations field.
func (r *queryResolver) SearchLocations(ctx context.Context, query string) ([]*LocationSearchResult, error) {
	if r.WeatherService == nil {
		return nil, fmt.Errorf("weather service not initialized")
	}

	if query == "" {
		return []*LocationSearchResult{}, nil
	}

	// Search using WeatherService (limit to 10 results)
	locations, err := r.WeatherService.SearchLocations(query, 10)
	if err != nil {
		return nil, fmt.Errorf("location search failed: %w", err)
	}

	// Convert to GraphQL type
	results := make([]*LocationSearchResult, 0, len(locations))
	for _, loc := range locations {
		region := loc.Admin1 // Use admin1 as region
		results = append(results, &LocationSearchResult{
			Name:    loc.Name,
			Region:  &region,
			Country: loc.Country,
			Lat:     loc.Latitude,
			Lon:     loc.Longitude,
		})
	}

	return results, nil
}

// IPGeolocation is the resolver for the ipGeolocation field.
func (r *queryResolver) IPGeolocation(ctx context.Context, ip *string) (*IPGeolocation, error) {
	if r.WeatherService == nil {
		return nil, fmt.Errorf("weather service not initialized")
	}

	// Validate IP address is provided
	if ip == nil || *ip == "" {
		return nil, fmt.Errorf("IP address is required")
	}

	// Lookup IP using WeatherService
	geoData, err := r.WeatherService.LookupIP(*ip)
	if err != nil {
		return nil, fmt.Errorf("IP geolocation failed: %w", err)
	}

	// Convert to GraphQL type
	city := geoData.City
	region := geoData.Region
	timezone := geoData.Timezone

	return &IPGeolocation{
		IP:          geoData.IP,
		City:        &city,
		Region:      &region,
		Country:     geoData.Country,
		CountryCode: geoData.CountryCode,
		Lat:         geoData.Latitude,
		Lon:         geoData.Longitude,
		Timezone:    &timezone,
	}, nil
}

// CurrentLocation is the resolver for the currentLocation field.
func (r *queryResolver) CurrentLocation(ctx context.Context) (*IPGeolocation, error) {
	if r.WeatherService == nil {
		return nil, fmt.Errorf("weather service not initialized")
	}

	// Get client IP from context (set by middleware)
	clientIP, ok := ctx.Value("client_ip").(string)
	if !ok || clientIP == "" {
		return nil, fmt.Errorf("client IP not available in context")
	}

	// Lookup IP using WeatherService
	geoData, err := r.WeatherService.LookupIP(clientIP)
	if err != nil {
		return nil, fmt.Errorf("IP geolocation failed: %w", err)
	}

	// Convert to GraphQL type
	city := geoData.City
	region := geoData.Region
	timezone := geoData.Timezone

	return &IPGeolocation{
		IP:          geoData.IP,
		City:        &city,
		Region:      &region,
		Country:     geoData.Country,
		CountryCode: geoData.CountryCode,
		Lat:         geoData.Latitude,
		Lon:         geoData.Longitude,
		Timezone:    &timezone,
	}, nil
}

// HistoricalWeather is the resolver for the historicalWeather field.
func (r *queryResolver) HistoricalWeather(ctx context.Context, location string, date string) (*HistoricalWeather, error) {
	if r.WeatherService == nil {
		return nil, fmt.Errorf("weather service not initialized")
	}

	// Parse the date (expected format: YYYY-MM-DD or MM-DD)
	var month, day, year int
	var err error

	// Try YYYY-MM-DD format first
	parsedDate, err := time.Parse("2006-01-02", date)
	if err != nil {
		// Try MM-DD format
		parsedDate, err = time.Parse("01-02", date)
		if err != nil {
			return nil, fmt.Errorf("invalid date format: %s (use YYYY-MM-DD or MM-DD)", date)
		}
		// Use current year if not specified
		year = time.Now().Year() - 1
	} else {
		year = parsedDate.Year()
	}
	month = int(parsedDate.Month())
	day = parsedDate.Day()

	// Get coordinates for location
	coords, err := r.WeatherService.GetCoordinates(location, "")
	if err != nil {
		return nil, fmt.Errorf("could not find location: %s", location)
	}

	// Get historical weather data for 1 year
	historical, err := r.WeatherService.GetHistoricalWeather(coords.Latitude, coords.Longitude, month, day, year, 1)
	if err != nil {
		return nil, fmt.Errorf("failed to get historical weather: %w", err)
	}

	// Check if we got any data
	if len(historical.Years) == 0 {
		return nil, fmt.Errorf("no historical data available for %s on %s", location, date)
	}

	// Use the first (and only) year's data
	histDay := historical.Years[0]

	// Build the response
	precipitation := histDay.Precipitation
	humidity := histDay.HumidityMean
	timezone := coords.Timezone

	return &HistoricalWeather{
		Location: &Location{
			Name:     coords.Name,
			Country:  coords.Country,
			Lat:      coords.Latitude,
			Lon:      coords.Longitude,
			Timezone: &timezone,
		},
		Date: histDay.Date,
		Day: &DayForecast{
			MaxTemp:            histDay.TempMax,
			MinTemp:            histDay.TempMin,
			TotalPrecipitation: &precipitation,
			ChanceOfRain:       &humidity, // Use humidity as proxy since historical data doesn't have chance of rain
			Condition: &WeatherCondition{
				Text: r.WeatherService.GetWeatherDescription(histDay.WeatherCode),
				Icon: stringPtr(r.WeatherService.GetWeatherIcon(histDay.WeatherCode, true)),
			},
		},
	}, nil
}

// LookupZipCode is the resolver for the lookupZipCode field.
func (r *queryResolver) LookupZipCode(ctx context.Context, code string) (*ZipCodeLookup, error) {
	if r.WeatherService == nil {
		return nil, fmt.Errorf("weather service not initialized")
	}

	// Parse zipcode string to int
	zipcode, err := strconv.Atoi(code)
	if err != nil {
		return nil, fmt.Errorf("invalid zipcode format: %s", code)
	}

	// Lookup zipcode using WeatherService
	coords, err := r.WeatherService.LookupZipcode(zipcode)
	if err != nil {
		return nil, fmt.Errorf("zipcode lookup failed: %w", err)
	}

	return &ZipCodeLookup{
		ZipCode: code,
		City:    coords.Name,
		State:   coords.Admin1,
		Country: coords.Country,
		Lat:     coords.Latitude,
		Lon:     coords.Longitude,
	}, nil
}

// LookupCoordinates is the resolver for the lookupCoordinates field.
func (r *queryResolver) LookupCoordinates(ctx context.Context, lat float64, lon float64) (*CoordinatesLookup, error) {
	if r.WeatherService == nil {
		return nil, fmt.Errorf("weather service not initialized")
	}

	// Validate coordinate ranges
	if lat < -90 || lat > 90 {
		return nil, fmt.Errorf("latitude must be between -90 and 90")
	}
	if lon < -180 || lon > 180 {
		return nil, fmt.Errorf("longitude must be between -180 and 180")
	}

	// Perform reverse geocoding
	coords, err := r.WeatherService.ReverseGeocode(lat, lon)
	if err != nil {
		return nil, fmt.Errorf("reverse geocoding failed: %w", err)
	}

	// Build result
	return &CoordinatesLookup{
		Lat:      coords.Latitude,
		Lon:      coords.Longitude,
		City:     &coords.Name,
		Region:   &coords.Admin1,
		Country:  coords.Country,
		Timezone: &coords.Timezone,
	}, nil
}

// Earthquakes is the resolver for the earthquakes field.
func (r *queryResolver) Earthquakes(ctx context.Context, minMagnitude *float64, limit *int) ([]*Earthquake, error) {
	if r.EarthquakeHandler == nil {
		return nil, fmt.Errorf("earthquake service not initialized")
	}

	if minMagnitude != nil && *minMagnitude < 0 {
		return nil, fmt.Errorf("minMagnitude must be non-negative")
	}

	if limit != nil && *limit < 0 {
		return nil, fmt.Errorf("limit must be non-negative")
	}

	earthquakes, err := r.EarthquakeHandler.ListEarthquakes("all_day", minMagnitude, limit)
	if err != nil {
		return nil, err
	}

	return mapGraphQLEarthquakes(earthquakes), nil
}

// Hurricanes is the resolver for the hurricanes field.
func (r *queryResolver) Hurricanes(ctx context.Context, active *bool) ([]*Hurricane, error) {
	if r.HurricaneHandler == nil {
		return nil, fmt.Errorf("hurricane service not initialized")
	}

	if active != nil && !*active {
		return nil, fmt.Errorf("inactive hurricanes are not available in the current runtime")
	}

	storms, err := r.HurricaneHandler.ListActiveStorms()
	if err != nil {
		return nil, err
	}

	return mapGraphQLHurricanes(storms), nil
}

// SevereWeather is the resolver for the severeWeather field.
func (r *queryResolver) SevereWeather(ctx context.Context, location *string) ([]*SevereWeather, error) {
	if r.SevereWeatherHandler == nil {
		return nil, fmt.Errorf("severe weather service not initialized")
	}

	locationQuery := ""
	if location != nil {
		locationQuery = *location
	}

	data, err := r.SevereWeatherHandler.GetSevereWeatherData(locationQuery)
	if err != nil {
		return nil, err
	}

	return mapGraphQLSevereWeather(data), nil
}

// MoonPhase is the resolver for the moonPhase field.
func (r *queryResolver) MoonPhase(ctx context.Context, date *string) (*MoonPhase, error) {
	if r.MoonHandler == nil {
		return nil, fmt.Errorf("moon service not initialized")
	}

	// Parse date or use current time
	targetDate := time.Now()
	if date != nil && *date != "" {
		// Try parsing common date formats
		formats := []string{"2006-01-02", "2006-01-02T15:04:05Z", time.RFC3339}
		for _, format := range formats {
			if parsed, err := time.Parse(format, *date); err == nil {
				targetDate = parsed
				break
			}
		}
	}

	// Get moon data (using 0,0 as default location since GraphQL query doesn't provide location)
	moonData := r.MoonHandler.GetMoonData(0, 0, targetDate)

	// Parse next moon dates from RFC3339 strings to time.Time
	var nextNewMoon, nextFullMoon *time.Time
	if nnn, err := time.Parse(time.RFC3339, moonData.NextNewMoon); err == nil {
		nextNewMoon = &nnn
	}
	if nfm, err := time.Parse(time.RFC3339, moonData.NextFullMoon); err == nil {
		nextFullMoon = &nfm
	}

	// Convert illumination from percentage (0-100) to fraction (0-1)
	illumination := moonData.Illumination / 100.0

	return &MoonPhase{
		Phase:        moonData.Phase,
		Illumination: illumination,
		Age:          &moonData.Age,
		Distance:     &moonData.Distance,
		Angle:        &moonData.AngularSize,
		Moonrise:     &moonData.Rise,
		Moonset:      &moonData.Set,
		NextNewMoon:  nextNewMoon,
		NextFullMoon: nextFullMoon,
	}, nil
}

// PublicUserProfile is the resolver for the publicUserProfile field.
func (r *queryResolver) PublicUserProfile(ctx context.Context, username string) (*PublicUserProfile, error) {
	viewerUserID := int64(getUserIDFromContext(ctx))

	profile, err := handler.LoadPublicUserProfile(r.UsersDB, username, viewerUserID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to load public user profile: %w", err)
	}

	return mapGraphQLPublicUserProfile(profile), nil
}

// ValidateUserInvite is the resolver for the validateUserInvite field.
func (r *queryResolver) ValidateUserInvite(ctx context.Context, token string) (*UserInviteValidation, error) {
	response, err := handler.ValidateAPIUserInvite(r.UsersDB, token)
	if err != nil {
		return nil, err
	}

	return mapGraphQLUserInviteValidation(response), nil
}

// ValidateServerInvite is the resolver for the validateServerInvite field.
func (r *queryResolver) ValidateServerInvite(ctx context.Context, token string) (*ServerInviteValidation, error) {
	response, err := handler.ValidateAPIServerInvite(token)
	if err != nil {
		return nil, err
	}

	return mapGraphQLServerInviteValidation(response), nil
}

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*models.User, error) {
	user, err := loadGraphQLCurrentUserAuth(ctx, r.UsersDB)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// CurrentUserAvatar is the resolver for the currentUserAvatar field.
func (r *queryResolver) CurrentUserAvatar(ctx context.Context) (*PublicAvatar, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized: user not authenticated")
	}

	avatar, err := handler.LoadCurrentUserAvatar(r.UsersDB, int64(userID))
	if err != nil {
		return nil, fmt.Errorf("failed to load current user avatar: %w", err)
	}

	return &PublicAvatar{
		Type: avatar.Type,
		Urls: avatar.URLs,
	}, nil
}

// CurrentUserTwoFactorStatus is the resolver for the currentUserTwoFactorStatus field.
func (r *queryResolver) CurrentUserTwoFactorStatus(ctx context.Context) (*TOTPStatus, error) {
	user, err := loadGraphQLCurrentUserAuth(ctx, r.UsersDB)
	if err != nil {
		return nil, err
	}

	status, err := handler.LoadCurrentUserTwoFactorStatus(r.UsersDB, user)
	if err != nil {
		return nil, fmt.Errorf("failed to load current user two-factor status: %w", err)
	}

	return mapGraphQLTOTPStatus(status), nil
}

// CurrentUserTwoFactorSetup is the resolver for the currentUserTwoFactorSetup field.
func (r *queryResolver) CurrentUserTwoFactorSetup(ctx context.Context) (*TOTPSetup, error) {
	user, err := loadGraphQLCurrentUserAuth(ctx, r.UsersDB)
	if err != nil {
		return nil, err
	}

	setup, err := handler.PrepareCurrentUserTwoFactorSetup(r.UsersDB, user)
	if err != nil {
		return nil, err
	}

	return mapGraphQLTOTPSetup(setup), nil
}

// CurrentUserPasskeys is the resolver for the currentUserPasskeys field.
func (r *queryResolver) CurrentUserPasskeys(ctx context.Context) ([]*UserPasskey, error) {
	user, err := loadGraphQLCurrentUserAuth(ctx, r.UsersDB)
	if err != nil {
		return nil, err
	}

	summaries, err := handler.ListUserPasskeys(r.UsersDB, user.ID)
	if err != nil {
		return nil, err
	}

	results := make([]*UserPasskey, 0, len(summaries))
	for _, summary := range summaries {
		mapped := mapGraphQLPasskey(summary)
		if mapped != nil {
			results = append(results, mapped)
		}
	}
	return results, nil
}

// UserSettings is the resolver for the userSettings field.
func (r *queryResolver) UserSettings(ctx context.Context) (*UserSettings, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized: user not authenticated")
	}

	settings, err := handler.LoadUserSettings(r.UsersDB, int64(userID))
	if err != nil {
		return nil, fmt.Errorf("failed to load user settings: %w", err)
	}

	return mapGraphQLUserSettings(settings), nil
}

// UserTokens is the resolver for the userTokens field.
func (r *queryResolver) UserTokens(ctx context.Context) ([]*UserToken, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized: user not authenticated")
	}

	rows, err := r.UsersDB.Query(`
		SELECT id, name, token_prefix, scopes, created_at, expires_at, last_used_at
		FROM user_tokens
		WHERE user_id = ?
		ORDER BY created_at DESC
	`, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to load user tokens: %w", err)
	}
	defer rows.Close()

	var tokens []*UserToken
	for rows.Next() {
		var id int64
		var name sql.NullString
		var tokenPrefix string
		var scopes sql.NullString
		var createdAt time.Time
		var expiresAt sql.NullTime
		var lastUsedAt sql.NullTime

		if err := rows.Scan(&id, &name, &tokenPrefix, &scopes, &createdAt, &expiresAt, &lastUsedAt); err != nil {
			return nil, fmt.Errorf("failed to scan user token: %w", err)
		}

		tokens = append(tokens, buildGraphQLUserToken(
			id,
			name.String,
			tokenPrefix,
			scopes.String,
			createdAt,
			expiresAt,
			lastUsedAt,
			nil,
		))
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("failed to iterate user tokens: %w", err)
	}

	return tokens, nil
}

// SavedLocations is the resolver for the savedLocations field.
func (r *queryResolver) SavedLocations(ctx context.Context) ([]*models.SavedLocation, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized: user not authenticated")
	}

	rows, err := r.UsersDB.Query(
		"SELECT id, user_id, name, latitude, longitude, alerts_enabled, created_at, updated_at FROM user_saved_locations WHERE user_id = $1 ORDER BY created_at DESC",
		userID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get saved locations: %w", err)
	}
	defer rows.Close()

	var locations []*models.SavedLocation
	for rows.Next() {
		var loc models.SavedLocation
		if err := rows.Scan(&loc.ID, &loc.UserID, &loc.Name, &loc.Latitude, &loc.Longitude, &loc.AlertsEnabled, &loc.CreatedAt, &loc.UpdatedAt); err != nil {
			continue
		}
		locations = append(locations, &loc)
	}

	return locations, nil
}

// SavedLocation is the resolver for the savedLocation field.
func (r *queryResolver) SavedLocation(ctx context.Context, id string) (*models.SavedLocation, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized: user not authenticated")
	}

	var loc models.SavedLocation
	err := r.UsersDB.QueryRow(
		"SELECT id, user_id, name, latitude, longitude, alerts_enabled, created_at, updated_at FROM user_saved_locations WHERE id = $1 AND user_id = $2",
		id, userID,
	).Scan(&loc.ID, &loc.UserID, &loc.Name, &loc.Latitude, &loc.Longitude, &loc.AlertsEnabled, &loc.CreatedAt, &loc.UpdatedAt)
	if err != nil {
		return nil, fmt.Errorf("saved location not found: %w", err)
	}

	return &loc, nil
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context) ([]*models.Notification, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized: user not authenticated")
	}

	rows, err := r.UsersDB.Query(
		"SELECT id, user_id, type, display, title, message, read, dismissed, created_at, expires_at FROM user_notifications WHERE user_id = $1 ORDER BY created_at DESC LIMIT 50",
		userID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get notifications: %w", err)
	}
	defer rows.Close()

	var notifications []*models.Notification
	for rows.Next() {
		var notif models.Notification
		var notificationUserID int
		if err := rows.Scan(
			&notif.ID,
			&notificationUserID,
			&notif.Type,
			&notif.Display,
			&notif.Title,
			&notif.Message,
			&notif.Read,
			&notif.Dismissed,
			&notif.CreatedAt,
			&notif.ExpiresAt,
		); err != nil {
			continue
		}
		notif.UserID = &notificationUserID
		notif.IsRead = notif.Read
		notifications = append(notifications, &notif)
	}

	return notifications, nil
}

// UnreadNotifications is the resolver for the unreadNotifications field.
func (r *queryResolver) UnreadNotifications(ctx context.Context) (*UnreadCount, error) {
	userID := getUserIDFromContext(ctx)
	if userID == 0 {
		return nil, fmt.Errorf("unauthorized: user not authenticated")
	}

	var count int
	err := r.UsersDB.QueryRow(
		"SELECT COUNT(*) FROM user_notifications WHERE user_id = $1 AND read = 0",
		userID,
	).Scan(&count)
	if err != nil {
		return nil, fmt.Errorf("failed to get unread count: %w", err)
	}

	return &UnreadCount{Count: count}, nil
}

// AdminUsers is the resolver for the adminUsers field.
func (r *queryResolver) AdminUsers(ctx context.Context) ([]*models.User, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	rows, err := r.UsersDB.Query(
		"SELECT id, email, username, role, email_verified, two_factor_enabled, created_at, updated_at FROM user_accounts ORDER BY created_at DESC",
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get users: %w", err)
	}
	defer rows.Close()

	var users []*models.User
	for rows.Next() {
		var user models.User
		if err := rows.Scan(&user.ID, &user.Email, &user.Username, &user.Role, &user.EmailVerified, &user.TwoFactorEnabled, &user.CreatedAt, &user.UpdatedAt); err != nil {
			continue
		}
		user.Email = utils.MaskEmail(user.Email)
		users = append(users, &user)
	}

	return users, nil
}

// AdminServerAdmins is the resolver for the adminServerAdmins field.
func (r *queryResolver) AdminServerAdmins(ctx context.Context) (*ServerAdminOverview, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	adminModel := &models.AdminModel{DB: r.ServerDB}
	count, err := adminModel.GetCount()
	if err != nil {
		return nil, fmt.Errorf("failed to count admins: %w", err)
	}

	currentAdmin, err := loadGraphQLCurrentAdmin(ctx, r.ServerDB)
	if err != nil {
		return nil, err
	}

	onlineAdmins, err := loadGraphQLOnlineAdminUsernames(r.ServerDB)
	if err != nil {
		return nil, fmt.Errorf("failed to load online admins: %w", err)
	}

	return &ServerAdminOverview{
		Count:         count,
		CurrentAdmin:  buildGraphQLServerAdmin(currentAdmin),
		OnlineAdmins:  onlineAdmins,
		PrivacyNotice: "Server admin account details are private. You may view your own account and see currently online admin usernames.",
	}, nil
}

// AdminServerAdmin is the resolver for the adminServerAdmin field.
func (r *queryResolver) AdminServerAdmin(ctx context.Context, id string) (*ServerAdmin, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	adminID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid admin id")
	}

	currentAdmin, err := loadGraphQLCurrentAdmin(ctx, r.ServerDB)
	if err != nil {
		return nil, err
	}
	if adminID != currentAdmin.ID {
		return nil, fmt.Errorf("server admin account details are private")
	}

	return buildGraphQLServerAdmin(currentAdmin), nil
}

// AdminUserInvites is the resolver for the adminUserInvites field.
func (r *queryResolver) AdminUserInvites(ctx context.Context) ([]*UserInvite, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	inviteModel := &models.UserInviteModel{DB: r.UsersDB}
	invites, err := inviteModel.ListInvites()
	if err != nil {
		return nil, fmt.Errorf("failed to load user invites: %w", err)
	}

	response := make([]*UserInvite, 0, len(invites))
	for i := range invites {
		invite := invites[i]
		response = append(response, buildGraphQLUserInvite(&invite, ctx))
	}

	return response, nil
}

// AdminUserInvite is the resolver for the adminUserInvite field.
func (r *queryResolver) AdminUserInvite(ctx context.Context, id string) (*UserInvite, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	inviteID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid invite id")
	}

	inviteModel := &models.UserInviteModel{DB: r.UsersDB}
	invite, err := inviteModel.GetByID(inviteID)
	if err != nil {
		return nil, fmt.Errorf("failed to load user invite: %w", err)
	}
	if invite == nil {
		return nil, nil
	}

	return buildGraphQLUserInvite(invite, ctx), nil
}

// AdminSettings is the resolver for the adminSettings field.
func (r *queryResolver) AdminSettings(ctx context.Context) ([]*models.Setting, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	rows, err := r.ServerDB.Query(
		"SELECT key, value, type, COALESCE(description, ''), updated_at FROM server_config ORDER BY key",
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get settings: %w", err)
	}
	defer rows.Close()

	var settings []*models.Setting
	for rows.Next() {
		setting, err := scanGraphQLSetting(rows.Scan)
		if err != nil {
			continue
		}
		settings = append(settings, setting)
	}

	return settings, nil
}

// AdminSetting is the resolver for the adminSetting field.
func (r *queryResolver) AdminSetting(ctx context.Context, key string) (*models.Setting, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	setting, err := loadGraphQLSetting(r.ServerDB, key)
	if err != nil {
		return nil, fmt.Errorf("setting not found: %w", err)
	}

	return setting, nil
}

// AdminTokens is the resolver for the adminTokens field.
func (r *queryResolver) AdminTokens(ctx context.Context) ([]*models.APIToken, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	adminID, ok := ctx.Value("admin_id").(int)
	if !ok || adminID <= 0 {
		return nil, fmt.Errorf("unauthorized: admin session required")
	}

	adminModel := &models.AdminModel{DB: r.ServerDB}
	admin, err := adminModel.GetByID(int64(adminID))
	if err != nil {
		return nil, fmt.Errorf("failed to load admin token metadata: %w", err)
	}

	if admin.APITokenPrefix == "" {
		return []*models.APIToken{}, nil
	}

	return []*models.APIToken{
		{
			ID:          int(admin.ID),
			Token:       "",
			TokenPrefix: admin.APITokenPrefix,
			CreatedAt:   admin.UpdatedAt,
		},
	}, nil
}

// AdminAuditLogs is the resolver for the adminAuditLogs field.
func (r *queryResolver) AdminAuditLogs(ctx context.Context, limit *int, offset *int) ([]*AuditLog, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	limitVal := 50
	if limit != nil {
		limitVal = *limit
	}
	offsetVal := 0
	if offset != nil {
		offsetVal = *offset
	}

	rows, err := r.ServerDB.Query(
		"SELECT id, actor_type, actor_id, action, resource_type, resource_id, details, ip_address, user_agent, timestamp FROM server_audit_log ORDER BY timestamp DESC LIMIT ? OFFSET ?",
		limitVal, offsetVal,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get audit logs: %w", err)
	}
	defer rows.Close()

	var logs []*AuditLog
	for rows.Next() {
		var log AuditLog
		var actorType sql.NullString
		var actorID sql.NullString
		var resourceType sql.NullString
		var resourceID sql.NullString
		var details sql.NullString
		var ip sql.NullString
		var userAgent sql.NullString
		if err := rows.Scan(&log.ID, &actorType, &actorID, &log.Action, &resourceType, &resourceID, &details, &ip, &userAgent, &log.CreatedAt); err != nil {
			continue
		}
		if actorType.Valid && actorType.String == "user" && actorID.Valid {
			if parsedUserID, err := strconv.Atoi(actorID.String); err == nil {
				log.UserID = &parsedUserID
			}
		}
		if resourceType.Valid {
			resource := resourceType.String
			if resourceID.Valid && strings.TrimSpace(resourceID.String) != "" {
				resource = fmt.Sprintf("%s:%s", resourceType.String, resourceID.String)
			}
			log.Resource = &resource
		}
		if details.Valid && strings.TrimSpace(details.String) != "" {
			log.Details = &details.String
		}
		if ip.Valid && strings.TrimSpace(ip.String) != "" {
			log.IP = &ip.String
		}
		if userAgent.Valid && strings.TrimSpace(userAgent.String) != "" {
			log.UserAgent = &userAgent.String
		}
		logs = append(logs, &log)
	}

	return logs, nil
}

// AdminStats is the resolver for the adminStats field.
func (r *queryResolver) AdminStats(ctx context.Context) (*SystemStats, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	var totalUsers, activeUsers int
	var adminUsers int
	var totalLocations int
	var totalNotifications int
	var unreadNotifications int

	userModel := &models.UserModel{DB: r.UsersDB}
	totalUsers, err := userModel.Count()
	if err != nil {
		return nil, fmt.Errorf("failed to count users: %w", err)
	}
	adminUsers, err = userModel.CountByRole("admin")
	if err != nil {
		return nil, fmt.Errorf("failed to count admin users: %w", err)
	}
	if err := r.UsersDB.QueryRow("SELECT COUNT(*) FROM user_accounts WHERE last_login_at > datetime('now', '-30 days')").Scan(&activeUsers); err != nil {
		return nil, fmt.Errorf("failed to count active users: %w", err)
	}
	if err := r.UsersDB.QueryRow("SELECT COUNT(*) FROM user_saved_locations").Scan(&totalLocations); err != nil {
		return nil, fmt.Errorf("failed to count saved locations: %w", err)
	}
	if err := r.UsersDB.QueryRow("SELECT COUNT(*) FROM user_notifications").Scan(&totalNotifications); err != nil {
		return nil, fmt.Errorf("failed to count notifications: %w", err)
	}
	if err := r.UsersDB.QueryRow("SELECT COUNT(*) FROM user_notifications WHERE read = 0").Scan(&unreadNotifications); err != nil {
		return nil, fmt.Errorf("failed to count unread notifications: %w", err)
	}

	requestStats, err := loadGraphQLRequestStats(r.ServerDB)
	if err != nil {
		return nil, fmt.Errorf("failed to load request stats: %w", err)
	}

	databaseStats, err := loadGraphQLDatabaseStats(r.ServerDB, r.UsersDB)
	if err != nil {
		return nil, fmt.Errorf("failed to load database stats: %w", err)
	}

	uptime := time.Since(handler.GetInitStatus().Started).Round(time.Second).String()
	var perUser *float64
	if totalUsers > 0 {
		value := float64(totalLocations) / float64(totalUsers)
		perUser = &value
	}

	return &SystemStats{
		Uptime:   uptime,
		Requests: requestStats,
		Users: &UserStats{
			Total:  totalUsers,
			Active: &activeUsers,
			Admins: &adminUsers,
		},
		Locations: &LocationStats{
			Total:   totalLocations,
			PerUser: perUser,
		},
		Notifications: &NotificationStats{
			Total:  totalNotifications,
			Unread: &unreadNotifications,
		},
		Database: databaseStats,
	}, nil
}

// AdminTasks is the resolver for the adminTasks field.
func (r *queryResolver) AdminTasks(ctx context.Context) ([]*ScheduledTask, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	rows, err := r.ServerDB.Query(
		"SELECT task_name, schedule, enabled, last_run, next_run, run_count, fail_count FROM server_scheduler_state ORDER BY task_name",
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get tasks: %w", err)
	}
	defer rows.Close()

	var tasks []*ScheduledTask
	for rows.Next() {
		task, err := scanGraphQLScheduledTask(rows.Scan)
		if err != nil {
			continue
		}
		tasks = append(tasks, task)
	}

	return tasks, nil
}

// AdminTaskHistory is the resolver for the adminTaskHistory field.
func (r *queryResolver) AdminTaskHistory(ctx context.Context, name string, limit *int) ([]*TaskHistory, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	if r.SchedulerHandler == nil || r.SchedulerHandler.Scheduler == nil {
		return nil, fmt.Errorf("scheduler runtime unavailable")
	}

	limitValue := 50
	if limit != nil && *limit > 0 {
		limitValue = *limit
	}

	historyRuns, err := r.SchedulerHandler.Scheduler.GetTaskHistory(name, limitValue)
	if err != nil {
		return nil, fmt.Errorf("failed to get task history: %w", err)
	}

	var history []*TaskHistory
	for _, run := range historyRuns {
		history = append(history, mapSchedulerTaskHistory(run))
	}

	return history, nil
}

// AdminChannels is the resolver for the adminChannels field.
func (r *queryResolver) AdminChannels(ctx context.Context) ([]*NotificationChannel, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	rows, err := r.ServerDB.Query(
		"SELECT channel_type, enabled, config FROM notification_channels ORDER BY channel_type",
	)
	if err != nil {
		return nil, fmt.Errorf("failed to get channels: %w", err)
	}
	defer rows.Close()

	var channels []*NotificationChannel
	for rows.Next() {
		channel, err := scanGraphQLNotificationChannel(rows.Scan)
		if err != nil {
			continue
		}
		channels = append(channels, channel)
	}

	return channels, nil
}

// AdminChannel is the resolver for the adminChannel field.
func (r *queryResolver) AdminChannel(ctx context.Context, typeArg string) (*NotificationChannel, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	channel, err := loadGraphQLNotificationChannel(r.ServerDB, typeArg)
	if err != nil {
		return nil, fmt.Errorf("channel not found: %w", err)
	}

	return channel, nil
}

// AdminChannelStats is the resolver for the adminChannelStats field.
func (r *queryResolver) AdminChannelStats(ctx context.Context, typeArg string) (*ChannelStats, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	var sent, failed int
	var lastSent sql.NullTime
	if err := r.ServerDB.QueryRow(`
		SELECT
			COUNT(CASE WHEN state = 'delivered' THEN 1 END),
			COUNT(CASE WHEN state IN ('failed', 'dead_letter') THEN 1 END),
			MAX(delivered_at)
		FROM notification_queue
		WHERE channel_type = ?
	`, typeArg).Scan(&sent, &failed, &lastSent); err != nil {
		return nil, fmt.Errorf("failed to load channel stats: %w", err)
	}

	var lastSentAt *time.Time
	if lastSent.Valid {
		lastSentAt = &lastSent.Time
	}

	return &ChannelStats{
		Sent:     sent,
		Failed:   failed,
		LastSent: lastSentAt,
	}, nil
}

// AdminQueueStats is the resolver for the adminQueueStats field.
func (r *queryResolver) AdminQueueStats(ctx context.Context) (*QueueStats, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	var pending, processing, completed, failed int
	if err := r.ServerDB.QueryRow("SELECT COUNT(*) FROM notification_queue WHERE state IN ('created', 'queued')").Scan(&pending); err != nil {
		return nil, fmt.Errorf("failed to load pending queue count: %w", err)
	}
	if err := r.ServerDB.QueryRow("SELECT COUNT(*) FROM notification_queue WHERE state = 'sending'").Scan(&processing); err != nil {
		return nil, fmt.Errorf("failed to load processing queue count: %w", err)
	}
	if err := r.ServerDB.QueryRow("SELECT COUNT(*) FROM notification_queue WHERE state = 'delivered'").Scan(&completed); err != nil {
		return nil, fmt.Errorf("failed to load completed queue count: %w", err)
	}
	if err := r.ServerDB.QueryRow("SELECT COUNT(*) FROM notification_queue WHERE state IN ('failed', 'dead_letter')").Scan(&failed); err != nil {
		return nil, fmt.Errorf("failed to load failed queue count: %w", err)
	}

	return &QueueStats{
		Pending:    pending,
		Processing: processing,
		Completed:  completed,
		Failed:     failed,
	}, nil
}

// AdminSMTPProviders is the resolver for the adminSMTPProviders field.
func (r *queryResolver) AdminSMTPProviders(ctx context.Context) ([]*SMTPProvider, error) {
	userRole, ok := ctx.Value("user_role").(string)
	if !ok || userRole != "admin" {
		return nil, fmt.Errorf("unauthorized: admin access required")
	}

	presets := service.ListProviderPresets()
	providers := make([]*SMTPProvider, 0, len(presets))
	for _, preset := range presets {
		port, err := strconv.Atoi(preset.Port)
		if err != nil {
			return nil, fmt.Errorf("invalid SMTP preset port %q for %s: %w", preset.Port, preset.Name, err)
		}

		providers = append(providers, &SMTPProvider{
			Name:   preset.Name,
			Host:   preset.Host,
			Port:   port,
			Secure: preset.UseTLS,
		})
	}

	return providers, nil
}

// AdminPasskeys is the resolver for the adminPasskeys field.
// Returns the passkeys registered for the currently authenticated admin.
func (r *queryResolver) AdminPasskeys(ctx context.Context) ([]*AdminPasskey, error) {
	admin, err := loadGraphQLCurrentAdmin(ctx, r.ServerDB)
	if err != nil {
		return nil, err
	}

	summaries, err := handler.ListAdminPasskeys(r.ServerDB, admin.ID)
	if err != nil {
		return nil, err
	}

	out := make([]*AdminPasskey, 0, len(summaries))
	for _, s := range summaries {
		out = append(out, mapGraphQLAdminPasskey(s))
	}
	return out, nil
}

// Lat is the resolver for the lat field.
func (r *savedLocationResolver) Lat(ctx context.Context, obj *models.SavedLocation) (float64, error) {
	return obj.Latitude, nil
}

// Lon is the resolver for the lon field.
func (r *savedLocationResolver) Lon(ctx context.Context, obj *models.SavedLocation) (float64, error) {
	return obj.Longitude, nil
}

// Country is the resolver for the country field.
func (r *savedLocationResolver) Country(ctx context.Context, obj *models.SavedLocation) (*string, error) {
	country := ""
	return &country, nil
}

// Region is the resolver for the region field.
func (r *savedLocationResolver) Region(ctx context.Context, obj *models.SavedLocation) (*string, error) {
	region := ""
	return &region, nil
}

// Alerts is the resolver for the alerts field.
func (r *savedLocationResolver) Alerts(ctx context.Context, obj *models.SavedLocation) (bool, error) {
	return obj.AlertsEnabled, nil
}

// UpdatedBy is the resolver for the updatedBy field.
func (r *settingResolver) UpdatedBy(ctx context.Context, obj *models.Setting) (*string, error) {
	// Setting doesn't have UpdatedBy field
	return nil, nil
}

// APIToken returns APITokenResolver implementation.
func (r *Resolver) APIToken() APITokenResolver { return &aPITokenResolver{r} }

// GenericResponse returns GenericResponseResolver implementation.
func (r *Resolver) GenericResponse() GenericResponseResolver { return &genericResponseResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Notification returns NotificationResolver implementation.
func (r *Resolver) Notification() NotificationResolver { return &notificationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// SavedLocation returns SavedLocationResolver implementation.
func (r *Resolver) SavedLocation() SavedLocationResolver { return &savedLocationResolver{r} }

// Setting returns SettingResolver implementation.
func (r *Resolver) Setting() SettingResolver { return &settingResolver{r} }

type aPITokenResolver struct{ *Resolver }
type genericResponseResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type notificationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type savedLocationResolver struct{ *Resolver }
type settingResolver struct{ *Resolver }
